### ISSUE TITLE
{ isError, error } from useQuery(...) doesn't catch errors

### ISSUE THREAD

**Issue by mlisthenewcool** [tannerlinsley/react-query#2258] opened 2021-05-10 07:28 UTC
**Describe the bug**

Following the official examples, errors aren't caught by useQuery() if you try to access a network that does not exist (Network Error from axios).

**To Reproduce**

```typescript
const fetchSomething = async (): Promise<MyType[]> => {
  const { data } = await axios.get<MyType[]>('..._api_url_...')
  return data
}

export const useSomething = (
  options?: UseQueryOptions<MyType[], AxiosError>
): UseQueryResult<MyType[], AxiosError> => {
  return useQuery('something', fetchSomething, options)
}

const SomethingComponent = (): JSX.Element => {
  const { isLoading, isSuccess, isError, error, data } = useSomething()

  if (isLoading) {
    return <div>loading...</div>
  }

  if (isSuccess) {
    console.log('isSuccess', isSuccess)
  }

  if (isError) {
    console.log('error', error)
    return <div>something went wrong</div>
  }

  if (!data) {
    return <div>data is undefined</div>
  }

  const filteredData = data.filter((d) => !!d)
  if (filteredData.length === 0) {
    return <div>there is no something yet</div>
  }

  return <div>it's ok</div>
}
```

**Comment by TkDodo** [comment] 2021-05-10 07:41
not sure what you mean. I forked the simple example, changed the url to something non-existing and see the error on the screen: https://codesandbox.io/s/recursing-dewdney-x5l5s?file=/src/index.js

please provide a minimal runnable example, but I'm gonna close this right away because this is a base functionality of the library which I'm very certain is working :)

**Closed by TkDodo** 2021-05-10 07:41 UTC

**Comment by ASchwad** [comment] 2022-02-10 09:47
@TkDodo Sorry for bringing up this old issue again, but I can reproduce the issue with the [official example Sandbox](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/simple) of this repository. It seems like 404, 403 and maybe other 4xx Status codes are not recognized as error. But maybe I have wrong expectations or im doing something wrong here...

1. Change fetch url to something non-existent like 
```
fetch(
      "https://api.github.com/repos/tannerlinsley/react-queryxxx"
    ).then((res) => res.json())
```
2. Although the query returns a 404 Status Code, the sandbox renders like a proper result was returned and shows the 👀 ✨ 🍴  emojis without text --> `error != true`
3. Logging the overall result of the useQuery with the URL of Step 1 yields the following object, where `data` contains the error message:
```
status: "success"
isLoading: false
isSuccess: true
isError: false
isIdle: false
data: Object
dataUpdatedAt: 1644485619606
error: null
errorUpdatedAt: 0
failureCount: 0
isFetched: true
isFetchedAfterMount: true
isFetching: false
isRefetching: false
isLoadingError: false
isPlaceholderData: false
isPreviousData: false
isRefetchError: false
isStale: true
refetch: ƒ bound refetch() {}
remove: ƒ bound remove() {}
```


I tried the behaviour also with these urls:
* No error rendered: http://httpstat.us/403; http://httpstat.us/404; https://api.github.com/repos/tannerlinsley/react-queryxxx
* Error rendered: http://httpstat.us/500

**Comment by TkDodo** [comment] 2022-02-10 12:55
react-query needs a rejected promise to show errors. libraries like `axios` treat 4xx status codes as failed promises, but `fetch` does not. please see:
- https://react-query.tanstack.com/guides/query-functions#usage-with-fetch-and-other-clients-that-do-not-throw-by-default

**Comment by travisdahl** [comment] 2022-04-14 01:09
@TkDodo probably a moot point since im on v2 but I think there is a bug with `usePaginatedQuery` (and possibly `mutate`)...

We have a generic fetch handler we use on all the request that throws/catches accordingly and it is working great with `useQuery` but with the fore-mentioned `error` and `isError` never seem to work properly though the `onError` handler does.

https://codesandbox.io/s/hungry-pond-j8xt55?file=/src/index.js

**Comment by uehlbran** [comment] 2023-12-16 23:10
Why was this closed? React Query should produce an error when getting back a status code of 4xx or 5xx. It makes no sense that isError is false in these situations.
