### ISSUE TITLE
Using data from useQurey as dependency of useEffect will cause useEffect endless running.

### ISSUE THREAD

**Issue by YagamiNewLight** [tannerlinsley/react-query#1916] opened 2021-03-07 11:26 UTC
**Describe the bug**

**Context**
My data model is based on the backend API data, which is got by the useQuery, There is a derived state based on the server data, which has it's own setter but depends on the backend source data as well. So I write my code as follows:
```
function App() {
  const [derivedState, setDerivedState] = useState({});
  const { data = {} } = useQuery(someService);
  useEffect(() => {
    console.log("side effect happening");
    setDerivedState(data);
  }, [data]);
  return <div>{derivedState}</div>
}
```
But I found that the useEffect hooks will run endlessly once I set default value for ```data```.

**To Reproduce**
Reproduce link: https://codesandbox.io/s/jolly-goldberg-56239?file=/src/index.js

**Expected behavior**
No endless running of the useEffect hooks.

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: chrome 
 - Version: 88.0.4324.190

**Additional context**
Note: Removal of the default value will not cause this problem.

**Comment by TkDodo** [comment] 2021-03-07 11:39
I don’t see an infinite loop when doing:

```
const { data = {} } = useQuery('key', service);
```

**Comment by YagamiNewLight** [comment] 2021-03-07 11:46
Hmmm, maybe it's a particular situation when using it with a custom hook, could you please check on the link I provided?

**Comment by TkDodo** [comment] 2021-03-07 12:08
I did and I don't have it. can you maybe provide an example where I don't need to change anything to reproduce the behaviour - maybe I'm doing that step differently than you?

That being said: when useQuery returns `undefined` for data, you assign it to an empty object, which is a new referential object every time. Then, you build an effect on top of it. Imo, this is bound to run more often then you'd expect (although not indefinitely).

I'm also not sure what problem you are trying to solve with this. Putting derived state into state and calculating it via useEffect is usually an antiPattern - `useMemo` would be a better fit.

I can assure you that `data` returned from useQuery is referentially stable if the same data structure has been returned by the query.

**Comment by TkDodo** [comment] 2021-03-07 12:25
Ok, i think i got something:

- react-query returns undefined
- You reassign to empty object 
- The effect runs
- The effect calls setState
- Your component re-renders
- react-query returns undefined
- You reassign to a new empty object
- The effect runs

Repeat a lot, but not indefinitely. It stops as soon as data arrives, and react-query returns the stable data.

**Comment by YagamiNewLight** [comment] 2021-03-07 12:27
Weird.....
Here's a [link ](https://codesandbox.io/s/dry-wave-f8b9g?file=/src/index.js)which you can directly see much much more console and errors without change any single line of code. 

Yes, I know it's kinda antiPattern. But in this way,  it's convenient for me to not mutate the data source here and then get the computed data using `useMeMo`. I wanna directly set my derived state, that's why I'm not using `useMemo`, maybe you could provide me some other way of doing this?

**Comment by YagamiNewLight** [comment] 2021-03-07 12:28
Yes, it would stop once the data arrived, but sometimes the browser just get crashed...

**Comment by TkDodo** [comment] 2021-03-07 19:23
You are not passing a key as the first argument to useQuery like I did ;)

i see many options how to fix this, but nobe of them have anything todo with the library itself. Here’s how I’d fix it:

```
const { data } = useQuery(...)
const derivedData = useMemo(() => ..., [data])
```

you can also do this with useEffect if you really want to. data can be undefined here so if you work with it, use optional chaining. 

If you must assign a default value to data, don’t use an inline object. The reference will change every render - extract it to a const outside of the react component and the effect will run only once.

**Closed by TkDodo** 2021-03-07 19:23 UTC

**Comment by YagamiNewLight** [comment] 2021-03-08 00:33
Sure I've already known the fix to that problem. 

The reason I put up with this issue is I think default value is not the reason of much render if  I use my own pure hooks, which you can find in my demo.

 So here I think it's the library which caused this issue and it's not very straightforward for people to locate where the issue is, cause default value is everywhere. 

If you don't think it's a library bug，maybe you could just warn the user on the doc in case they run into my condition.

**Comment by dusty** [comment] 2021-03-08 00:47
Try this

only set if something comes in
```
function useDerivedState(service) {
  const [derivedState, setDerivedState] = useState({});
  // if replace useMyHook with useQuery, the side effect will running endlessly
  const { data } = useQuery(service);
  useEffect(() => {
    console.log("side effect happeni1ng");
    if (data) setDerivedState(data);
  }, [data]);
  return [derivedState];
}
```

or

pull it up to make it stable
```
const defaultState = {}
function useDerivedState(service) {
  const [derivedState, setDerivedState] = useState({});
  // if replace useMyHook with useQuery, the side effect will running endlessly
  const { data = defaultState  } = useQuery(service);
  useEffect(() => {
    console.log("side effect happeni1ng");
    setDerivedState(data);
  }, [data]);
  return [derivedState];
}
```

**Comment by YagamiNewLight** [comment] 2021-03-08 05:42
> Try this
> 
> only set if something comes in
> 
> ```
> function useDerivedState(service) {
>   const [derivedState, setDerivedState] = useState({});
>   // if replace useMyHook with useQuery, the side effect will running endlessly
>   const { data } = useQuery(service);
>   useEffect(() => {
>     console.log("side effect happeni1ng");
>     if (data) setDerivedState(data);
>   }, [data]);
>   return [derivedState];
> }
> ```
> 
> or
> 
> pull it up to make it stable
> 
> ```
> const defaultState = {}
> function useDerivedState(service) {
>   const [derivedState, setDerivedState] = useState({});
>   // if replace useMyHook with useQuery, the side effect will running endlessly
>   const { data = defaultState  } = useQuery(service);
>   useEffect(() => {
>     console.log("side effect happeni1ng");
>     setDerivedState(data);
>   }, [data]);
>   return [derivedState];
> }
> ```
> 
> or
> 
> move it to the setDerivedState call
> 
> ```
> function useDerivedState(service) {
>   const [derivedState, setDerivedState] = useState({});
>   // if replace useMyHook with useQuery, the side effect will running endlessly
>   const { data } = useQuery(service);
>   useEffect(() => {
>     console.log("side effect happeni1ng");
>     setDerivedState(data || {});
>   }, [data]);
>   return [derivedState];
> }
> ```

Thanks for your solutions, I had taken the first solution in my code.

But just as I mentioned above, it's not Intuitive for me when writing code like that, I believe most of the people who write react hooks would not have this consideration when they implement derived state using ```useEffect``` and the default value. 

Again, the reason I come up with this issue is I think the default value is NOT the reason for much render. Because if I use my own hook, the much render disappeared.  I'm not a react hooks expert, maybe my implementation is too simple to reach the core problem of this bug. It's Intuitive for me to write code like that, so I want the running result is also Intuitive, and it would be great if the library can do the work to keep my coding intuition.

**Comment by TkDodo** [comment] 2021-03-08 05:54
In your custom solution, you initialize the state with `null`, so you never assign the default value object, because this:

`const { data = {} } = useMyHook(service);`

only assigns empty object if data is `undefined`

basically, this effect will always run:

```
const obj ={}
useEffect(() => console.log('effect'), [obj])
```

**Comment by YagamiNewLight** [comment] 2021-03-11 02:37
@TkDodo, yes you are totally right. Thanks for your in-time and patient answer. Cheers.
