### ISSUE TITLE
despite setting the enabled option to false, useQuery still initiates a fetch

### ISSUE THREAD

**Issue by aastronaut** [tannerlinsley/react-query#1196] opened 2020-10-21 16:33 UTC
**Describe the bug**
After an update to `2.23.1` or `3.2.0-beta.3` I noticed that passing the option `{ enabled: false }` to `useQuery` will still initiate a request when the component mounts. Where this flag was enough to prevent the hook from causing a request on mount in an earlier version (`2.5.13` in my case), now I would need to create a separate component and mount it conditionally in order to regain the same wanted behavior, which would result in a lot of boilerplate.

**To Reproduce**
(on request if unclear)

**Expected behavior**
I would expect the option `{ enabled: false }` to disable fetching completely, as that would prevent the creation of an conditionally mounted component. However, the expected behavior is unclear to me due to mismatching descriptions in docs and source code:

According to the docs *automatically running* is mentioned:
```
enabled: Boolean | unknown
    Set this to false to disable this query from automatically running.
    Actually it can be anything that will pass a boolean condition. See Dependent Queries for more information.
```

According to the source code *automatic refetching* is mentioned:
```typescript
/**
 * Set this to `false` to disable automatic refetching when the query mounts or changes query keys.
 * To refetch the query, use the `refetch` method returned from the `useQuery` instance.
 * Defaults to `true`.
 */
enabled?: boolean | unknown
```

**A clear and concise description of what you expected to happen.**
Please either adapt the docs to mention that only *refetching* is controlled with this option, or a fix is needed for the hook to control also the fetching behavior when a component mounts.

**Comment by TkDodo** [comment] 2020-10-25 06:17
Queries that are mounted with `enabled: false` should start in the `idle` state and should not fetch until it is enabled. This is used for orchestrating dependent queries, where you don’t have all the data to make a request initially. 

So this seems like a bug to me. Can you make a codesandbox to reproduce maybe?

**Comment by TkDodo** [comment] 2020-10-25 15:51
So, I just tested this with the latest beta (`3.2.0-beta.12`) and it works fine, have a look here: https://codesandbox.io/s/happy-browser-k286h

We start the query in `idle` state because `enabled` is false, and there is no request. Click the button, see the request in the browser devtools.

Maybe you were setting `enabled` to a `falsy` value rather than really setting it to `false` ? This is a breaking change in v3 (stated here: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#queryoptionsenabled). Falsy values will no longer work, it needs to really be the boolean value `false`.

This sentence:

> Actually it can be anything that will pass a boolean condition. See Dependent Queries for more information.

has also been removed from the v3 docs. It now states:

![Screenshot 2020-10-25 at 16 50 55](https://user-images.githubusercontent.com/1021430/97112014-491d2980-16e2-11eb-9313-dcee3ed26f9d.png)

**Comment by KingAmo** [comment] 2020-10-26 12:17
same bug to me, `enable: false ` is set, useQuery still initiates a fetch,  `   "react-query": "^2.23.1",`

**Comment by TkDodo** [comment] 2020-10-26 18:29
@KingAmo here is the same example from above with react-query `2.23.1`: https://codesandbox.io/s/funny-bird-0ulmy

Seems to work like advertised.

If you are having problems, please create a codesandbox example of your own where the issue is reproducible.

**Comment by KingAmo** [comment] 2020-10-27 11:51
> @KingAmo here is the same example from above with react-query `2.23.1`: https://codesandbox.io/s/funny-bird-0ulmy
> 
> Seems to work like advertised.
> 
> If you are having problems, please create a codesandbox example of your own where the issue is reproducible.

sorry, my fault, i use `refetch` in some `useEffect`, so there is still a `initial`  fetch;

**Comment by dadamssg** [comment] 2020-10-29 17:06
seems like `enabled` is ignored when you pass the configuration as an object: https://codesandbox.io/s/rough-pine-f4uf9

**Comment by TkDodo** [comment] 2020-10-29 19:29
Also, as discussed on Discord, the object syntax has changed from nested (v2) to flat (v3), see: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#query-object-syntax

I think we can close this issue.

**Comment by evliu** [comment] 2020-10-29 23:59
> Also, as discussed on Discord, the object syntax has changed from nested (v2) to flat (v3), see: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#query-object-syntax
> 
> I think we can close this issue.

But what if you are not using query object syntax? The main docs themselves don't use an object
https://react-query-beta.tanstack.com/reference/useQuery

**Comment by evliu** [comment] 2020-10-30 00:34
Actually it looks like my version of this bug is when i'm using `usePaginatedQuery`, either with object syntax or not

**Comment by TkDodo** [comment] 2020-10-30 06:00
Okay, can you post an example with that please? FYI, there will be no `usePaginatedQuery` in v3, it’s just `useQuery` with `keepPreviousData` set to `true`: https://react-query-beta.tanstack.com/guides/migrating-to-react-query-3#usepaginatedquery

**Comment by evliu** [comment] 2020-10-30 16:00
I just used the example for Pagination in the docs and set enabled to false hardcode

**Comment by TkDodo** [comment] 2020-10-31 20:10
> I just used the example for Pagination in the docs and set enabled to false hardcode. I'll just upgrade to v3.

If that's all you did, why can't you fork the example and post the link here to the non-working version? That would make it a lot easier for us ...

Anyways, I did exactly that: https://codesandbox.io/s/sleepy-wave-z16lt

You'll end up in a runtime error if you only do that, because you are in `idle` state then, and the example doesn't check that. So I added that check too. Apart from that, I only have one query now in idle state and _there is no network request_ ...

So unless someone can show me a runnable example where something is clearly not working, or I am completely misunderstanding something here, we should close this issue please.

**Comment by evliu** [comment] 2020-10-31 20:12
I agree with closing the issue

**Closed** 2020-11-03 20:57 UTC

**Comment by aleksandrenko** [comment] 2023-09-27 14:45
Sorry to bring back this again. But I'm able to reproduce it and it's an issue in my app.

Refresh with open dev-tools/console
https://codesandbox.io/s/dry-fast-mc2yy9?file=/src/index.js

**Comment by TkDodo** [comment] 2023-09-27 15:09
you're using a very old version (v2). v5 is around the corner. In v2, options weren't flat:

```
  return useQuery(
    ["test"],
    () => {
      console.log("BUT STILL RUNNING THE QUERY FN");

      return "hello";
    },
    { enabled: false }
  );
```

please upgrade; we're not really supporting v2 anymore

**Comment by daniel-ricado** [comment] 2023-10-26 03:14
having the same issue on v4 with useQueries:
"@tanstack/react-query": "^4.32.6",


    const queryResults = useQueries({
        queries: [
          {
            queryKey: ['settings'],
            queryFn: async () => {
                const res: any = await fetch('http://something')
                return res 
            },
            enabled: false,
            cacheTime: 0
          },
          {
            queryKey: ['data'],
            queryFn: async () => {
                const res: any = await fetch('http://something')

                return res
            },
            enabled: false,
            cacheTime: 0
          },
        ],
    })

**Comment by TkDodo** [comment] 2023-10-26 06:12
@daniel-ricado then show a reproduction with v4 please.

**Comment by thuc201995** [comment] 2023-11-14 23:05
same bug

"@tanstack/react-query@^4.24.6":
  version "4.36.1"
  resolved "https://registry.yarnpkg.com/@tanstack/react-query/-/react-query-4.36.1.tgz#acb589fab4085060e2e78013164868c9c785e5d2"
  integrity sha512-y7ySVHFyyQblPl3J3eQBWpXZkliroki3ARnBKsdJchlgt7yJLRDUcf4B8soufgiYt3pEQIkBWBx1N9/ZPIeUWw==
  dependencies:
    "@tanstack/query-core" "4.36.1"
    use-sync-external-store "^1.2.0"

**Comment by andrewzey** [comment] 2023-11-22 17:38
I am also having this issue, where a disabled query (`enabled` passed an explicit `false`) is making a network request. As i dig into this, I'll see if I can provide clean repro steps.

**Comment by moussa32** [comment] 2024-01-11 00:47
unfortunately this happend again and the bug returned

**Comment by martyjg** [comment] 2024-01-12 19:03
This is occurring for me also. Seems to happen if a query is used elsewhere in another component (maybe because it is cached?). I've updated to the V5 `useQuery` format also.

**Comment by ewof** [comment] 2024-01-19 22:22
same here

**Comment by alxHenry** [comment] 2024-01-20 01:08
> This is occurring for me also. Seems to happen if a query is used elsewhere at the same time in another component (maybe because it is cached?). I've updated to the V5 `useQuery` format also.

I was having this same issue, but it ended up being how I was using `initialData` in my queries. I had an "observer" hook with `useQueries` that listened to a bunch of queries and `enabled: false` so that the observers never triggered a fetch. Then I had separate components where those queries were actually fetched from with an enabled `useQuery`. I was passing an `initialData` to the enabled queries with `staleTime: Infinity`.

My expected behavior would be that the initial data for the enabled queries would be set and not go stale, then the observer queries would see the initial data and nothing else until a user initiated more fetching. What actually was happening was that all of the enabled queries were fetching when they rendered.

Passing the same `initialData` to both the observer queries and the enabled queries fixed this. I think the root of the issue was that the observer queries were rendering first, without `initialData`. Then when the enabled queries were rendered after, their `initialData` would be ignored because a query with that key was already initialized. From the enabled query's perspective, they had no data and needed to fetch.

Here's an [example repro](https://codesandbox.io/p/devbox/awesome-wave-fpxlvd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrld954900083p6hyiyr8mgj%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrld954800023p6h3xbf2his%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrld954800053p6hbe685owy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrld954800073p6h2bd6714a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrld954800023p6h3xbf2his%2522%253A%257B%2522id%2522%253A%2522clrld954800023p6h3xbf2his%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrld954800073p6h2bd6714a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrld954800063p6hwpyqt0q5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrld954800073p6h2bd6714a%2522%252C%2522activeTabId%2522%253A%2522clrld954800063p6hwpyqt0q5%2522%257D%252C%2522clrld954800053p6hbe685owy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrld954800033p6hjtk1fyhg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clrld954800043p6hmld48pb7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrju797n0008e8jigfcl5n5z%2522%257D%255D%252C%2522id%2522%253A%2522clrld954800053p6hbe685owy%2522%252C%2522activeTabId%2522%253A%2522clrld954800033p6hjtk1fyhg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), hopefully it helps someone.

**Comment by TkDodo** [comment] 2024-01-20 12:47
That's an interesting case @alxHenry, but it's pretty straightforward to understand the behaviour once we know how `initialData` works under the hood:

`initialData` only does something when a query entry in the cache is first created. Usually, a query is created with no data and `pending` state, but if we have initialData, that will be taken with `success` state.

A query will only be created when there is no cache entry for that query yet, or if it e.g. has been garbage collected before. The assignment literally happens in the constructor of `new Query()`, that will be invoked when a query is put into the cache for the first time.

When an observer is created, enabled or not, it will also refer to to (watch 👀) a query. If that doesn't exist, it will be created.

So in your case, the disabled observers are mounted first, so they create the Query. They have no initialData, so it's likely just `pending`.

Then, your other query comes and passes `initialData`, but this "does nothing" because the Query already exists in the cache.

**Comment by alxHenry** [comment] 2024-01-20 14:16
That’s what I suspected. I agree it’s a user error, not a bug in the library. Hopefully the comment can help someone else running into a similar issue. 

In a large codebase with deep nesting of components and contexts, the order of mounting isn’t obvious and often time isn’t even considered by the dev. I think that’s why I was surprised by the initial behavior I saw.

**Comment by TkDodo** [comment] 2024-01-20 14:17
I can recommend abstracting queries away into re-usable objets with the query options API (new in v5), then using them in all places:

https://tkdodo.eu/blog/the-query-options-api

**Comment by vladfaust** [comment] 2024-03-08 16:00
FYI, this solved my case (I'm using infinite queries): https://stackoverflow.com/a/72893761/3645337. 

<img width="680" alt="image" src="https://github.com/TanStack/query/assets/7955682/0ecf7658-6279-4043-91f2-7cb0ac1a8ffb">

**Comment by daniel-ricado** [comment] 2024-03-14 21:08
For anyone stuck on this, here was the first workaround

const [fetchContidition, setFetchCondition] = useState(false)

```
...
// reason to start the fetch
setFetchCondition(true)
...

const queryResults = useQueries({
    queries: [
      {
        queryKey: ['settings'],
        queryFn: async () => {
            if (!fetchCondition) {
               return
            }
            
            const res: any = await fetch('http://something')
            return res 
        },
        cacheTime: 0
      },
    ],
})
```

to the devs sorry I couldn't get a example going for you, but in reality we're all dealing with private data and working full time, so commiting a bunch of time to the working example that can be shared publicly is probably not a task anyone outside of collaborators would want to take on in place of just using the workaround or writing a fetch method that takes just a few minutes.

this library is great when you want to finely control request caching but if you're just doing a poll then the fetch api is probably the better option. (which is what we did in our scenario, ditching the workround for a simple fetch and timer)

Since the devs have long closed this issue and moved on to newer versions, can only recommend this type of workaround, doubt we'll see any fix for this version.

**Comment by Ab0o0o0oD** [comment] 2024-03-18 23:40
> For anyone stuck on this, here was the first workaround
> 
> const [fetchContidition, setFetchCondition] = useState(false)
> 
> ```
> ...
> // reason to start the fetch
> setFetchCondition(true)
> ...
> 
> const queryResults = useQueries({
>     queries: [
>       {
>         queryKey: ['settings'],
>         queryFn: async () => {
>             if (!fetchCondition) {
>                return
>             }
>             
>             const res: any = await fetch('http://something')
>             return res 
>         },
>         cacheTime: 0
>       },
>     ],
> })
> ```
> 
> to the devs sorry I couldn't get a example going for you, but in reality we're all dealing with private data and working full time, so commiting a bunch of time to the working example that can be shared publicly is probably not a task anyone outside of collaborators would want to take on in place of just using the workaround or writing a fetch method that takes just a few minutes.
> 
> this library is great when you want to finely control request caching but if you're just doing a poll then the fetch api is probably the better option. (which is what we did in our scenario, ditching the workround for a simple fetch and timer)
> 
> Since the devs have long closed this issue and moved on to newer versions, can only recommend this type of workaround, doubt we'll see any fix for this version.

I am using the "@tanstack/react-query" version "^4.33.0" and have same issue. Using the workaround provided by @daniel-ricado has offered some relief; however, it remains suboptimal.

**Comment by Dev-Jariwala** [comment] 2024-03-23 11:26
![Screenshot 2024-03-23 165258](https://github.com/TanStack/query/assets/112694731/bfcec602-14c7-45a1-853a-13f2823f209c)
here i want to store results for that data of userFound for only mobile_number where digits are equal to 10
but happens this 
![Screenshot 2024-03-23 165445](https://github.com/TanStack/query/assets/112694731/6eab3a75-9a34-4338-a667-ae8170650bda)
yes its not call api because i have restricted it in function itself but i dont want it to cache that {} empty objects also to reduce performance plz help asap

**Comment by grayey** [comment] 2024-04-08 17:50
I've faced the same issue. For me the issue was that if the `enabled` condition is `undefined` at any time (which happened sometimes), the query runs. This is understandable since `undefined` unsets the `enabled` property and `useQuery` will follow default behaviour which is `enabled=true`. My solution was to create a tiny helper function that returns `false` if the condition was undefined.

`export const queryIsEnabled = (condition = false): boolean => condition;`

used as `{
enabled: queryIsEnabled(condition),
}`

**Comment by hthief** [comment] 2024-05-16 19:33
I was in the middle of writing a post about this same issue on v4.36.1 but managed to trace the issue to a refetch inside a useEffect that was triggering when I shouldn't. Figure that could help out someone if they find themselves in the same situation.

**Comment by danvc** [comment] 2024-05-17 23:34
I was also facing the same situation here.. then I ended finding that I was using `refetch`. I think that `refetch` should respect `enabled`

**Comment by TkDodo** [comment] 2024-05-18 07:42
> I think that `refetch` should respect `enabled`

then you would have no way to imperatively trigger a fetch for a query that is enabled:false. While this is not a pattern I'd recommend, it's still something that is supported and documented

**Comment by Sina-Abf** [comment] 2024-07-13 10:14
![image](https://github.com/user-attachments/assets/50a7819c-2507-4da6-87b3-e4f2a925f679)
this fixed my problem
@tanstack/react-query: ^5.40.0

**Comment by faarda** [comment] 2024-07-18 01:36
https://github.com/TanStack/query/issues/1196#issuecomment-1889807769

I have the same problem described by @martyjg here. Whenever there's another instance of useQuery being declared, the query runs automatically.

**Comment by TkDodo** [comment] 2024-07-18 12:57
show a reproduction please

**Comment by csantos-nydig** [comment] 2024-08-05 14:20
cross-referencing from the discussion I created: https://github.com/TanStack/query/discussions/7855

https://codesandbox.io/p/sandbox/elegant-cdn-5hhvhh

```
const useDataQuery = (props) => {
  return useSuspenseQuery({
    queryFn: () => {
      return { a: 1, b: 2, c: 3 };
    },
    queryKey: ["test"],
    ...props,
  });
};

const ComponentOne = () => {
  const { data } = useDataQuery();

  return <div>ComponentOne {JSON.stringify(data)} </div>;
};

const ComponentTwo = () => {
  const { data } = useDataQuery({
    enabled: false,
    select: (data) => {
      console.log("inside Component2 select method");
      return data.a + data.b;
    },
  });

  return <div>ComponentTwo {JSON.stringify(data)} </div>;
};
```

RENDERS:
```
ComponentOne {"a":1,"b":2,"c":3}
ComponentTwo 3
```

----

And even if I comment out `ComponentOne` entirely; I still see RENDERED:
```
ComponentTwo 3
```
