### ISSUE TITLE
Query Key

### ISSUE THREAD

**Issue by adeepika1991** [tannerlinsley/react-query#1131] opened 2020-10-04 10:52 UTC
I am assigning a query key in string for a fetch function in useQuery(). But the query key is splitting and adding into the data. 

![reactQuery3](https://user-images.githubusercontent.com/15820580/95013432-3dbc6e00-060e-11eb-9a77-808a14e9fa36.JPG)

![reaactQuery2](https://user-images.githubusercontent.com/15820580/95013373-d1416f00-060d-11eb-9e9c-31b0ea03273e.JPG)

My data is like in the above picture. The query string i assigned is 'files'. Which is splitted and adding itself into data array.

I used useQuery() Hook before and never faced this issue. Is there any way i can rectify this?

**Comment by tannerlinsley** [comment] 2020-10-04 18:19
Can you please make a codesandbox that shows this issue?

**Comment by esvyridov** [comment] 2020-10-05 18:05
@adeepika1991 if I'm not mistaken the first argument of `queryFn` is a key. Based on this implementation of `fetchData` https://github.com/adeepika1991/search-GDrive/blob/18e890b45ae1a6968a3054d9312b9582d99ea287/src/fetchData.js#L21 the key (files) is destructed here https://github.com/adeepika1991/search-GDrive/blob/18e890b45ae1a6968a3054d9312b9582d99ea287/src/fetchData.js#L23 and that's the reason of result which you got (`[...'files', ...response.files]`)

**Comment by tannerlinsley** [comment] 2020-10-05 20:49
Either way, it's too hard to tell exactly how you are arriving at this result without some code to look at or a reproduction in codesandbox. With that said, I'm going to close this issue for triage, but feel free to reopen a new one with code/sandbox.

**Closed by tannerlinsley** 2020-10-05 20:49 UTC
