### ISSUE TITLE
useErrorBoundary and retry=false: reset doesn't work if an error was caused by being Offline

### ISSUE THREAD

**Issue by Shaddix** [tannerlinsley/react-query#2222] opened 2021-05-01 08:40 UTC
**Describe the bug**
Resetting error boundary doesn't re-fetch the query if an error was caused by being Offline (and retry=false). The fallback UI is still displayed after user is already Online and Reset button is pressed.

This is probably somewhat related to #2179.

**To Reproduce**
1. Go to https://stmgh.csb.app/
1. Open Chrome Dev Tools, disable cache, set Throttle to Offline (or disable All Network Adapters on your PC. Disabling cache is needed anyway)
1. Click on refetch
1. Fallback UI is displayed
1. Set Throttle to 'No Throttle' in Dev. tools.
1. Press Reset.
1. Fallback UI is still displayed, according to Dev Tools no API request is being actually sent.

**Expected behavior**
Fallback UI should immediately disappear, API request should be sent, 'loading...' should be shown, which should change to displaying actual data once the API call succeeds.

Or as discussed in #2179 maybe the query shouldn't switch to error or fetching state at all, if the user is currently offline.

This is probably just another scenario to consider when deciding about #2179.

**Comment by TkDodo** [comment] 2021-05-08 18:59
I could not reproduce this anymore with the above sandbox on v3.16.0. Possibly has been fixed with the merge of #2147.

**Closed by TkDodo** 2021-05-08 18:59 UTC
