### ISSUE TITLE
getQuerydata undefined on route change - NextJs

### ISSUE THREAD

**Issue by stiveurkel** [tannerlinsley/react-query#2072] opened 2021-04-02 00:08 UTC
Hi,

I'm using NextJs to create a chat app. Left hand side are chat rooms and right hand side is the current chat room opened. When a user type a messager I call useMutation() with onmutate where I use optimistic update. So far so good, I cancel the queries, setQueryData, then onsuccess invalidate queries.

However as soon as I change room, call router.push and try sending a mutation.mutate(data) again it fails 
It fails because in my onmutate function, setQueryData("mykey", oldData) -> oldData is undefined.

Is there a way to persist the queryData on route change ? Especially because there was no page refresh. So I don't understand why getQueryData is now undefined.

**Comment by TkDodo** [comment] 2021-04-02 05:53
Do you have a reproduction please? Where are you creating your queryClient?

**Comment by stiveurkel** [comment] 2021-04-02 07:56
Tricky to reproduce quickly as there are websocket and it's quite a big structure. Will try with a simplified version.

In the meantime I'm creating my query client in _app.js.

In [id].js I fetch chat rooms and current room messages server side. I have 2 components:
ChatMedsages.js and ChatRooms.js

 Inside the ChatMessages component I use useInfiniteQuery and useMutation fetching messages from the current room.id. Basically all works great until I call router.push and try mutateAddMessage.mutate(data) again... Optimistic update fails as old data are undefined.

**Comment by rodymolenaar** [comment] 2021-04-06 08:24
@TkDodo I ran into this issue in my application as well. This only seems to happen when navigating to the same component (re-render, vs. re-mount).

My reproduction shows that the queryCache contains the correct data, but useQuery isn't aware of it after a query key change.

https://codesandbox.io/s/usequery-hydration-bug-fqf6i

**Comment by rodymolenaar** [comment] 2021-04-06 08:25
I think https://github.com/tannerlinsley/react-query/issues/1978 is related  or a duplicate

**Comment by TkDodo** [comment] 2021-04-06 08:38
@rodymolenaar thanks for the reproduction. I could solve the issue by moving the queryClient creation from the function `MyApp` to _outside_ of it:

https://codesandbox.io/s/goofy-swirles-xzpir?file=/pages/_app.js

it's the only change I made.

As far as I understand it, it's fine to create a new QueryClient in `getServerSideProps`, because you only dehydrate it. On the frontend though, the cache must stay stable. You can also see that in my version, the devtools now correctly show all queries, while in your version, it was only showing the post with id 1. I'm viewing the hydration as basically "spreading" the state that we get from the backend over the state we have on the frontend. By keeping the cache stable, we just "add" values to the cache with every page transition. My experience with NextJs is limited (okay - nonexistent to be honest) - apologies if that analogy is incorrect :)

**Comment by rodymolenaar** [comment] 2021-04-06 08:55
Ah yes, you're right. I've been previously aware of this fact.

However, I think our concern with creating the QueryClient outside of the MyApp function was that it causes the same QueryClient instance to be used for all users. Not sure if this is a legitimate concern, however it did solve our instability issues.

I found

```
const queryClientRef = React.useRef();

if (!queryClientRef.current) {
  queryClientRef.current = new QueryClient();
}
```

at https://react-query.tanstack.com/examples/nextjs#_top

So it seems this has been figured out, but it looks like it isn't documented anywhere else.

**Comment by TkDodo** [comment] 2021-04-06 09:24
you can also use state to lazily initialize a queryClient (and potentially create a new one in an effect when the user changes), I've written about that here: https://tkdodo.eu/blog/use-state-for-one-time-initializations

it is also advisable to clear the cache with `queryClient.removeQueries` when a user logs out to avoid sharing that data.

**Comment by rodymolenaar** [comment] 2021-04-06 10:29
> you can also use state to lazily initialize a queryClient (and potentially create a new one in an effect when the user changes), I've written about that here: https://tkdodo.eu/blog/use-state-for-one-time-initializations
> 
> it is also advisable to clear the cache with `queryClient.removeQueries` when a user logs out to avoid sharing that data.

I'd like to rephrase my previous comment:
> However, I think our concern with creating the QueryClient outside of the MyApp function was that it causes the same 
> QueryClient instance to be used for all users. Not sure if this is a legitimate concern, however it did solve our instability 
> issues.

The issue we were experiencing probably had to do with SSR. The QueryClient outside of the custom app component would not change for every render on the server and create React hydration issues when the server's QueryClient had different data than the client's. Because of this, we were forced to create the QueryClient inside of the render function.

Seeing the Github issues where unstable QueryClient instances is the most probable cause, it might warrant putting this information somewhere in the docs. Since just lifting the QueryClient out of the custom app component is also probably problematic.

------

I believe you could also use this (shorter) syntax to initialize once:

```
const resource = React.useRef(new Resource());
```

**Comment by TkDodo** [comment] 2021-04-06 11:47
please PR to the docs if you think they can be improved 👍 

> I believe you could also use this (shorter) syntax to initialize once:

It can, but bear in mind that `useRef´ doesn't have a lazy initializer. So the `new Resource()` will be created each render, and then discarded. Might not matter, but it also might. I prefer `useState` for that :)

**Comment by rodymolenaar** [comment] 2021-04-06 14:24
> please PR to the docs if you think they can be improved 👍
> 
> > I believe you could also use this (shorter) syntax to initialize once:
> 
> It can, but bear in mind that `useRef` doesn't have a lazy initializer. So the `new Resource()` will be created each render, and then discarded. Might not matter, but it also might. I prefer `useState` for that :)

Ah check, learned something new :)

I'll try and find this information a good home in the docs, thanks!

**Comment by rodymolenaar** [comment] 2021-04-06 14:39
> > please PR to the docs if you think they can be improved 👍
> > > I believe you could also use this (shorter) syntax to initialize once:
> > 
> > 
> > It can, but bear in mind that `useRef` doesn't have a lazy initializer. So the `new Resource()` will be created each render, and then discarded. Might not matter, but it also might. I prefer `useState` for that :)
> 
> Ah check, learned something new :)
> 
> I'll try and find this information a good home in the docs, thanks!

@TkDodo Actually this was already added to the docs in February, I just completely missed it 🤡 

> Create a new QueryClient instance inside of your app, and on an instance ref. This ensures that data is not shared between different users and requests.

https://github.com/tannerlinsley/react-query/commit/862bb2be3a7c6161b70a2310f4661859adb6d943#diff-f8a7d7140c7558298858c319f0ab8931140c6dd6dbc87598ec4bddc346ad60ad

**Comment by TkDodo** [comment] 2021-04-06 15:30
oh very nice, now I've learned that we need to do it _inside_ the app, but it has to be stay stable :)

So I'll close this issue as we've found the solution I guess

**Closed by TkDodo** 2021-04-06 15:30 UTC

**Comment by chchaeun** [comment] 2022-09-09 14:06
> Hi,
> 
> I'm using NextJs to create a chat app. Left hand side are chat rooms and right hand side is the current chat room opened. When a user type a messager I call useMutation() with onmutate where I use optimistic update. So far so good, I cancel the queries, setQueryData, then onsuccess invalidate queries.
> 
> However as soon as I change room, call router.push and try sending a mutation.mutate(data) again it fails It fails because in my onmutate function, setQueryData("mykey", oldData) -> oldData is undefined.
> 
> Is there a way to persist the queryData on route change ? Especially because there was no page refresh. So I don't understand why getQueryData is now undefined.

I'm having the same problem, have you solved it?

**Comment by chchaeun** [comment] 2022-09-09 14:21
> Hi,
> 
> I'm using NextJs to create a chat app. Left hand side are chat rooms and right hand side is the current chat room opened. When a user type a messager I call useMutation() with onmutate where I use optimistic update. So far so good, I cancel the queries, setQueryData, then onsuccess invalidate queries.
> 
> However as soon as I change room, call router.push and try sending a mutation.mutate(data) again it fails It fails because in my onmutate function, setQueryData("mykey", oldData) -> oldData is undefined.
> 
> Is there a way to persist the queryData on route change ? Especially because there was no page refresh. So I don't understand why getQueryData is now undefined.

Hi. I'm having the same problem. Have you solved it?
