### ISSUE TITLE
TypeError cannot read property "queryCache" of undefined

### ISSUE THREAD

**Issue by ThomasEddie** [tannerlinsley/react-query#2058] opened 2021-03-31 02:59 UTC
**Describe the bug**
I wonder why I can't use destructuring with useQueryClient?

**Error Code**
```
export const useDeleteCategory = () => {
  const {invalidateQueries} = useQueryClient();
  const mutate = useMutation(
    ["delete_Category"],
    (id: number) => deleteData({ id, url: "category/delete" }),
    {
      onSuccess: () => {
        invalidateQueries("get_all_category");
      },
    }
  );
  return mutate;
};
```

**Work Code**
```
export const useDeleteCategory = () => {
  const queryClient = useQueryClient();
  const mutate = useMutation(
    ["delete_Category"],
    (id: number) => deleteData({ id, url: "category/delete" }),
    {
      onSuccess: () => {
        queryClient.invalidateQueries("get_all_category");
      },
    }
  );
  return mutate;
};
```

**Expected behavior**
When I destructuring useQueryClient it always gets an error when I delete data in API

**Screenshots**
<img width="620" alt="Screen Shot 2021-03-31 at 9 54 57 AM" src="https://user-images.githubusercontent.com/65760336/113084093-8cd30c80-9207-11eb-955e-539fc99a7470.png">

**Desktop (please complete the following information):**
 - OS: BigSur 
 - Browser: [ chrome]
 - Version: [11.2.3]

**Additional context**
```
{
   "dependencies":{
      "react-query": "^3.12.0",
      "react": "^17.0.1",

  }
}
```

**Comment by TkDodo** [comment] 2021-03-31 05:07
duplicate of https://github.com/tannerlinsley/react-query/issues/1575

**Closed by TkDodo** 2021-03-31 05:07 UTC
