### ISSUE TITLE
status is success when passing a falsy value

### ISSUE THREAD

**Issue by tatchi** [tannerlinsley/react-query#298] opened 2020-03-30 18:48 UTC
Hello, I noticed that the `status` is set to `success` when we pass a falsy value as first argument. It seems misleading to me since in this case, the request has not been made yet.

Example:

```js
const Posts: React.FC = ({ postId }) => {
  const result = useQuery(postId ? ["posts", postId] : null, fetchPostById);

  if (result.status === "loading") {
    return <div>Loading...</div>;
  }

  if (result.status === "success") {
    // data here is undefined
    console.log(result.data);
    return <div>{result.data.title}</div>;
  }

  return <div>Error</div>;
};
```

I would have expected to have data when the `status` is `success` (that's also how the current typescript definitions are implemented).

What about introducing another state (eg `notAsked` or `idle`) to represent that? It would mean that we could be in one of these 4 states:

1. NotAsked: data and error and both undefined
2. Loading: data and error and both undefined
3. Success: data has value and error is undefined
4. Error: data is undefined and error has value

I haven't played so much yet with the library, but I know that besides that there are also cached values that probably complicate things..

**Comment by cherniavskii** [comment] 2020-03-30 19:17
Duplicate of https://github.com/tannerlinsley/react-query/issues/280

**Comment by tatchi** [comment] 2020-03-30 20:03
Thanks for pointing out :)

I agree with @tannerlinsley that the user could use the query key to determine the UI. But I think that having another specific state would be better, especially for the typescript definitions.

The current typescript definitions make the assumption that `data` property is defined when the `status` is `success`.  The following three states are defined:

```typescript
export interface QueryLoadingResult<TResult> extends QueryResultBase<TResult> {
    status: 'loading';
    data: TResult | undefined; // even when error, data can have stale data
    error: unknown | null; // it still can be error
}

export interface QueryErrorResult<TResult> extends QueryResultBase<TResult> {
    status: 'error';
    data: TResult | undefined; // even when error, data can have stale data
    error: unknown;
}

export interface QuerySuccessResult<TResult> extends QueryResultBase<TResult> {
    status: 'success';
    data: TResult;  // <- data are defined here
    error: null;
}
```
The nice thing is that typescript can infer that data is defined when we check for the `status` to be `success`:

```typescript
if(result.status === 'success'){
   // typescript can infer that result.data is defined here
}
```

The problem with how the library works now, is that we would probably have to change the type definitions to account for the case when data is `undefined`. It would make things less convenient:

```typescript
  if (result.status === 'success') {
    // data can be undefined here..
    if (queryKey) {
      /* we know that if status is success and queryKey is defined
        we should have data. But TS can't infer that which mean
        that we would have to add an extra test
      */
      if (result.data) {
        // ok we have data
      }
    }
  }
```

We could then make this a bit more convenient and check that `status` is `success` and `data` truthy:

```typescript
  if (result.status === 'success') {
    // data can be undefined here..
    if (result.data) {
       // typescript knows that data should be defined here which is good.
    }
  }
```

But what if actually our API endpoint might return `undefined` (could be a valid returned value). We would not be able to distinguish between a request that has not been sent yet (status === `success` and data is `undefined`) from one that has resolved with an `undefined` value.

I'm not sure that all of what I wrote is correct and I know that there's a workaround as mentioned in #280 but just wanted to share my thought.

**Comment by cherniavskii** [comment] 2020-03-30 20:12
I don't use Typescript, so can't add anything here.

Regarding checking success status - I don't usually check if `status === success` when writing components - instead I check `loading` and `error` statuses and return something else if needed.


> But what if actually our API endpoint might return undefined (could be a valid returned value).

If you're using JSON - `undefined` isn't valid value

**Comment by tannerlinsley** [comment] 2020-04-01 15:50
I think this is resolved. There are multiple workarounds already for what seems to be a trivial problem for now. We'll consider this in future versions.

**Closed by tannerlinsley** 2020-04-01 15:50 UTC
