### ISSUE TITLE
`isFetching` returns wrong value when component is mounted with previously fetched key

### ISSUE THREAD

**Issue by kolbasan** [tannerlinsley/react-query#3269] opened 2022-02-06 11:46 UTC
### Describe the bug

We are using `useQuery` (with `refetchOnMount: false`) and the same query key is used for both parent and child components.
The parent has logic where only when `isFetching: true`  the child is rendered.
First render (with key "`a`") and first key change (to key "`b`") are working as expected, however when we change the key back to previous value (to "`a`"): for a brief moment the parent gets `isFetching: true` while child get `isFetching: false`

### Your minimal, reproducible example

https://codesandbox.io/s/is-fetching-bug-hqv1v?file=/src/App.js

### Steps to reproduce

On first render the console log looks this way:
```
parent isFetching=true 
child isFetching=true 
Starting fetch 
parent isFetching=false 
```
First time clicking "Change key" button we get:
```
parent isFetching=true 
child isFetching=true 
Starting fetch 
parent isFetching=false 
```
Second time clicking "Change key" shows unexpected behavior:
```
parent isFetching=true 
child isFetching=false 
Starting fetch 
parent isFetching=true 
child isFetching=true 
parent isFetching=false 
```

### Expected behavior

When clicking the "Change key" for the second time, we expect the same result as the first time it was clicked:
```
parent isFetching=true 
child isFetching=true 
Starting fetch 
parent isFetching=false 
```
However for the parent and child get different values for `isFetching`

### How often does this bug happen?

Every time

### Platform

- Chrome: Version 95

### react-query version

v3.34.12

**Comment by TkDodo** [comment] 2022-02-06 12:11
The codesandbox link shows an empty app. Have you saved it?

**Comment by kolbasan** [comment] 2022-02-07 08:08
@TkDodo Sorry, I've updated the codesandbox link

**Comment by TkDodo** [comment] 2022-02-08 19:55
I can reproduce it, even on later versions and with react18, where batching has improved. So it's not that. Also you can turn `refetchOnMount` back on and the issue persists.

It's seems to be a weird case that has to do with the conditional mounting + having cached data available already. I don't have time to look into this right now, so any help is appreciated

**Comment by rkulinski** [comment] 2022-02-08 20:21
It seems that it works correctly with `refetchOnMount: true`. It's possible that there's a race condition somewhere. Although I agree with @TkDodo that this is very unusual case. I haven't found any cause of that yet, but I'll poke around.

**Comment by rkulinski** [comment] 2022-02-12 13:54
So far I was able to find that `queryCache` object contains `false` value for `isFetching`. When `refetchOnMount` is false this piece of a code is not executed:
```
      if (fetchOnMount || fetchOptionally) {
        isFetching = true
```

so `isFetching` keeps `false` value. For me it seems like there's some issue with updating `queryCache`. I need to investigate it more.

**Comment by rkulinski** [comment] 2022-02-20 14:56
I was able to narrow it down to `updateResult` function. I believe the issue is with this part from `src/core/queryObserver.ts`:
```
  updateResult(notifyOptions?: NotifyOptions): void {
    const prevResult = this.currentResult as
      | QueryObserverResult<TData, TError>
      | undefined

    this.currentResult = this.createResult(this.currentQuery, this.options)
    this.currentResultState = this.currentQuery.state
```

`this.currentResult.isFetching` holds `true` value, but `this.currentQuery.state.isFetching` is still holding `false` value.

It seems to me that there are two ways of fixing that problem:
1. Use `this.currentResult` values instead of `this.currentQuery.state` to update `this.currentResultState`.
2. When setting `isFetching` manually while doing:
```
      if (fetchOnMount || fetchOptionally) {
        isFetching = true
```
add following line:
```
this.currentQuery.state.isFetching = isFetching
```

**Comment by TkDodo** [comment] 2022-02-20 15:13
> Solution number 2 seems to do the job, although it seems a bit hacky, on the other hand we already patching isFetching flag here, so it make sense to update it inside a query.

hm, the code in question is in `createResult` on the observer level when optimistically creating the result (which happens for the first fetch, before the first fetch so that we instantly get a `loading` state even though we haven't started fetching yet). There, we really shouldn't modify the state of the currentQuery because a) there can be multiple observers, some going optimistically into fetching state and some don't and b) this is called during render, so we should no have side-effects there that change the value in the cache.

**Comment by rkulinski** [comment] 2022-02-20 15:18
Got it, make sense. I'm still learning the codebase, but for sure we need to set that loading state somewhere. The issue reported here is because second query is pulling query state from cache (and doesn't call `isFetching = true`, due to the fact that `fetchOnMount` is `false`) where `isFetching` is still `false`. So it seems like we should make a fix inside `updateResult`?

**Comment by TkDodo** [comment] 2022-02-20 15:25
> The issue reported here is because second query is pulling query state from cache (and doesn't call isFetching = true, due to the fact that fetchOnMount is false) where isFetching is still false

Ah got it, I understand now. I have to think about it a bit. Maybe we need to store the `optimisticResult` itself on the cache or so. This is something that we might need to do anyways for react18 where subscriptions go to `currentResult`, but we actually also return the `optimisticResult`, so we technically _should_ subscribe to that.

I'm trying to think of situations where two observers can get different optimistic results though, and I'm sure there are some. Like, if the second observer mounts as `enabled: false` maybe or so ...

**Comment by TkDodo** [comment] 2022-02-20 15:39
Like:
- when we read optimistically and `fetchOnMount || fetchOptionally`, we store the crated optimistic result
- if other observers mount, we read that saved value
- we clear the optimistic result after the fetch

Not sure if that's a good idea - we would still perform the side-effect of writing something to the cache during render with that solution :/

---

But actually, it is interesting that we have one observer where we say: yes, this will be going into `fetching` state, so we return that optimistically, and then we have another observer that does not get that state because the real fetching hasn't started yet and it uses different options. That is a weird case to solve...

**Comment by rkulinski** [comment] 2022-02-20 18:05
If I'm getting this right, it seems like there should be a decision about weather optimistic update of some query should be propagated to cache (so it's state can be accessed via other queries)?

Maybe a solution would be to use optimistic query values (stored somewhere in some way) for all queries expect ones that would explicitly resign from optimistic updates?

**Comment by TkDodo** [comment] 2022-02-21 06:38
> If I'm getting this right, it seems like there should be a decision about weather optimistic update of some query should be propagated to cache (so it's state can be accessed via other queries)?

I currently don't see how that's possible. optimistic result calculation happens during rendering. If we write that result into some cache, we will have a side-effect during render. with react18, that will likely bite us with concurrent features. A render can start and be interrupted at any point, which means we might start a render, that writes to the cache, but never completes, which makes everything non-deterministic.

question: would we expect `shouldFetchOnMount` or `shouldFetchOptionally` to be `true` here? And what about is the value of `const mounted` ?

**Comment by rkulinski** [comment] 2022-02-21 20:26
In case of second query (the problematic one) in the beginning `mounted` has `false` value and `shouldFetchOnMount`, `shouldFetchOptionally` are `false`.

After a couple of renders and `mounted` is true, but `shouldFetchOnMount` and `shouldFetchOptionally` return `false`.
For that case I guess `shouldFetchOnMount` should be false, but `shouldFetchOptionally` should be `true`? If so should that be based on another query that is run in parent component?


I think I might have been confusing things, because my mental model was that if query in parent component is called and same query is run in child it should just return statuses of the query from the parent, but I think I get it now.

I would see two paths now:
1. We accept it as expected behavior (since query shouldn't been run on mount it has to wait until `isFetching` is set in query cache by another query.
2. We add some condition to render logic for such case, but we would have to somehow pull that information from query in parent component - it seems a bit problematic with current approach.

**Comment by TkDodo** [comment] 2022-02-21 21:51
If mounted is true that means we have another observer already - likely the parent component. So maybe it makes sense to check here if any other observer has fetchOnMount or fetchOptionally set to true, and if they do, we optimistically put the child observer into fetching as well...

**Comment by rkulinski** [comment] 2022-02-24 17:55
That make sense. I'll investigate that.

**Comment by rkulinski** [comment] 2022-02-27 17:39
Inside `createResult` I haven't found any way to access `isFetching` value from parent component query in any way (where the value would be true). Even listeners don't provide such info.

To fix that issue we have to find some mechanism to enable sharing query state different than using cache. I'm searching and debugging function calls before `createResult`, although I wasn't able to find anything in there which would allow pass a data to `createResult` in order to pull `isFetching` value from the parent component query.

**Comment by rkulinski** [comment] 2022-03-14 19:18
I made some more debugging and I think I made a mistake. `mounted` is true, but unfortunately not instantly. So issue will still persist. Moreover the only observer was the query itself. I think this bug might be more sophisticated than just updating queryObserver "if" condition. We would have to find a way to communicate that `isFetching` state that is set during a rendering:
```
        isFetching = true
```

**Comment by rkulinski** [comment] 2022-03-26 13:38
I think I've found something. While debugging I noticed that listener (for parent query) is added after `useQuery` is called for a children in `useEffect` (file: `useBaseQuery.ts`)

```
  React.useEffect(() => {
    mountedRef.current = true

    errorResetBoundary.clearReset()

    const unsubscribe = observer.subscribe(
      notifyManager.batchCalls(() => {
        if (mountedRef.current) {
          forceUpdate(x => x + 1)
        }
      })
    )

    // Update result to make sure we did not miss any query updates
    // between creating the observer and subscribing to it.
    observer.updateResult()

    return () => {
      mountedRef.current = false
      unsubscribe()
    }
  }, [errorResetBoundary, observer])
```

As a test I added listener when creating it inside `useState` initialisation

```
  const [observer] = React.useState(() => {
      const _observer = new Observer<TQueryFnData, TError, TData, TQueryData, TQueryKey>(
        queryClient,
        defaultedOptions
      )
    mountedRef.current = true

    errorResetBoundary.clearReset()
    debugger;
    _observer.subscribe(
      notifyManager.batchCalls(() => {
        if (mountedRef.current) {
          forceUpdate(x => x + 1)
        }
      })
    )
      return _observer;
    }
  )
```

We would have to somehow handle `unsubscribe`, but doing this seems to making a test pass. I haven't followed all possible consequences of this, but from investigation it seems the problem is that we have a delay in adding a listener.

After that change query in child component is receiving `isFetching == true`.

@TkDodo does that sound somehow reasonable?

**Comment by TkDodo** [comment] 2022-03-26 13:43
I'm afraid not. creating a subscription might trigger a fetch, so we have to do this in an effect. Also, with react18, the whole effect becomes one call to useSyncExternalStore, which we have to do to be compatible with concurrent features.

**Comment by TkDodo** [comment] 2022-04-03 07:33
so I don't really see any way forward with this. It looks like its an edge case that we kinda have to accept for now due to how we set the value of isFetching optimistically.

One workaround I found to make this work consistently is to determine isFetching with `useIsFetching` instead:

```
const isFetching = useIsFetching(key) > 0;
```

here is a sandbox reproduction of your issue, yielding consistent results: https://codesandbox.io/s/is-fetching-bug-forked-ocunx0?file=/src/App.js

note that there are some more re-renders, but this gets better on react 18, which has automatic batching. This sandbox, using react 18 and our v4 beta shows the following output, consistently:

```
parent isFetching=false 
Starting fetch 
parent isFetching=true 
child isFetching=true 
parent isFetching=false 
```

https://codesandbox.io/s/is-fetching-bug-forked-unm5cy?file=/src/App.js

As you can see, there is an additional `parent isFetching=false` output at the beginning, which is to be expected, because `useIsFetching` does not set the fetching state to `true` optimistically - which is what would cause the mentioned problem.

I hope this is an acceptable workaround. Closing for now, but feel free to keep the discussion going if you have some new input.

**Closed by TkDodo** 2022-04-03 07:33 UTC
Labels: bug, help wanted
