### ISSUE TITLE
Infinity staleTime and cacheTime still hit server

### ISSUE THREAD

**Issue by lukasa1993** [tannerlinsley/react-query#1677] opened 2021-01-22 08:52 UTC
```
useQuery(['test_query', href],
    () => testQuery(href), {
      staleTime:                   Infinity,
      cacheTime:                   Infinity,
      keepPreviousData: true,
      enabled:          !!href
    })
```

this still hits server every time and in browser network tab till it finishes download it doesn't show image

**Comment by TkDodo** [comment] 2021-01-22 09:09
please provide a reproducible codesandbox example. The react-query-devtools can also help narrow it down because they show you which state your query is in.

**Comment by lukasa1993** [comment] 2021-01-22 09:11
i cant provide reproducible sample its private api. `react-query-devtools` also confirms that it refetches every time, i can grab any data from devtools if you point me to it

**Comment by TkDodo** [comment] 2021-01-22 09:13
> i cant provide reproducible sample its private api.

You can always "mock" out your actual queryFn in the example:

```
const testQuery = (href) => Promise.resolve(some-test-data-goes-here)
```

**Comment by lukasa1993** [comment] 2021-01-22 09:22
not sure i follow if i mock it its not reproducible i am using creat-react-app and react-router in root i have
```
<QueryClientProvider client={queryClient}>
<BrowserRouter>
</BrowserRouter>
      <ReactQueryDevtools initialIsOpen={false} />
    </QueryClientProvider>
```
queryClient has no options provided
```const queryClient = new QueryClient();```

**Comment by TkDodo** [comment] 2021-01-22 09:26
I just meant stubbing out the actual ajax request (replace `axios.get` with something that statically returns a Promise). We don't need to see it in the network tab - the devtools will show us when it's fetching. As the actual data layer is rarely the problem and also what's "private" about your code, this should suffice.

side question: is your queryClient maybe created _inside_ your `App` function instead of _outside_ of it?

**Comment by lukasa1993** [comment] 2021-01-22 09:30
no its outside app function

**Comment by lukasa1993** [comment] 2021-01-23 14:07
@TkDodo is axios required i am not using axios

**Comment by TkDodo** [comment] 2021-01-23 14:21
No, this was just an example. All you need is a function that returns a Promise - doesn’t matter how.

**Comment by lukasa1993** [comment] 2021-01-23 14:24
i am trying… i picked basic example from repo but it was missing `eslint-config-prettier` this dependency and even that wish 7kb data still refetches as is, i only added `staleTime: Infinity, cacheTime: Infinity,` on each useQuery still refetches still browser hits server

**Comment by TkDodo** [comment] 2021-01-23 15:02
Do you have the codesandbox link please

**Comment by lukasa1993** [comment] 2021-01-23 16:28
https://github.com/lukasa1993/react-query-test

**Comment by lukasa1993** [comment] 2021-01-23 16:31
@TkDodo dependencies are outdates but its from this repos basic sample

**Comment by tannerlinsley** [comment] 2021-01-23 16:32
It will hit the server at least once or even retry a few times until it’s successful.

Tanner Linsley

**Comment by lukasa1993** [comment] 2021-01-23 16:33
> It will hit the server at least once or even retry a few times until it’s successful. Tanner Linsley
> […](#)

its successful every time it hits

**Comment by TkDodo** [comment] 2021-01-23 16:35
I've taken that code and put it in a codesandbox: https://codesandbox.io/s/pedantic-heyrovsky-bvj5q?file=/src/index.js

one image is fetched when the page loads, and the query is then marked as `fresh` and is _never_ refetched. So what exactly am I supposed to see here please?

**Comment by TkDodo** [comment] 2021-01-23 16:36
I've taken that code and put it in a codesandbox: https://codesandbox.io/s/pedantic-heyrovsky-bvj5q?file=/src/index.js

one image is fetched when the page loads, and the query is then marked as `fresh` and is _never_ refetched. So what exactly am I supposed to see here please?

**Comment by lukasa1993** [comment] 2021-01-23 16:36
its always refetched when i try

**Comment by TkDodo** [comment] 2021-01-23 16:38
the codesandbox works in safari and in chrome

I'm not sure - are you expecting to _not_ hit the server when you refresh the browser or something?

**Comment by lukasa1993** [comment] 2021-01-23 16:39
yea i do otherwise whats the point of cache ?

**Comment by tannerlinsley** [comment] 2021-01-23 16:40
I think you've misunderstood the purpose of React Query. It operates a cache per session, not per device (though this is experimentally possible with this new plugin: https://react-query.tanstack.com/plugins/persist-localstorage#_top

**Comment by lukasa1993** [comment] 2021-01-23 16:41
how you define session ?

**Comment by TkDodo** [comment] 2021-01-23 16:42
you could've saved us all a bunch of time by clearly stating the result that you are expecting to see and the steps to reproduce your behaviour. At no time in our conversation did you even mention that you are refreshing the browser.

As Tanner said, you can use the experimental plugin to persist data to the localstorage of your browser to "survive" page reloads.

**Comment by tannerlinsley** [comment] 2021-01-23 16:43
Sorry let me be even more specific. The cache is in-memory and only exists within the life of the javascript context for a tab. If you refresh, hard-navigate (not using pushState or replaceState history apis), or close/open the tab, it will not persist.

**Closed by TkDodo** 2021-01-23 16:42 UTC

**Comment by lukasa1993** [comment] 2021-01-23 16:43
you can save everyone a lot of time to say you don't have caching…

**Comment by lukasa1993** [comment] 2021-01-23 16:44
> Sorry let me be even more specific. The cache is in-memory and only exists within the life of the javascript context for a tab. If you refresh, hard-navigate (not using pushState or replaceState history apis), or close/open the tab, it will not persist.

make that more clear it doesn't say that anywhere

**Comment by tannerlinsley** [comment] 2021-01-23 16:46
@lukasa1993 I'm sorry it wasn't clear, but I can reliably say that this is the first instance I've encountered that the context of React Query's caching was misunderstood.

**Comment by tannerlinsley** [comment] 2021-01-23 16:52
I will admit that this is a general assumption many make within the space of Javascript and React tools. I can't tell you many tools in the ecosystem that actually come with any data *persistence* that don't come right out and say it. For example, PouchDB: https://pouchdb.com/. So within that context, I firmly believe it's not necessary to document this.

Welp, on with Saturday! 🎉  Have a good one everyone!

**Comment by lukasa1993** [comment] 2021-01-23 16:54
> I will admit that this is a general assumption many make within the space of Javascript and React tools. I can't tell you many tools in the ecosystem that actually come with any data _persistence_ that don't come right out and say it. For example, PouchDB: https://pouchdb.com/. So within that context, I firmly believe it's not necessary to document this.
> 
> Welp, on with Saturday! 🎉 Have a good one everyone!

REMIX …

**Comment by tannerlinsley** [comment] 2021-01-23 17:04
Locking this thread to avoid things getting off topic. If you (or anyone who finds themselves here) would like to open a PR to improve the docs on this topic where you see fit, please feel free to do so.
