### ISSUE TITLE
Thoughts on mutate function not handling rejected promises

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/react-query#121] opened 2020-02-01 00:13 UTC
Hey Tanner! Loving this library so far. Just spend the last little but with a snag on the fact that `mutate` propagates rejected promises. No big deal because I can handle those errors myself, however I don't see any reason for react-query to not just handle them for us. [For example](https://codesandbox.io/s/lively-sunset-8irld)

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import {useMutation} from 'react-query'

function failingMutation() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(new Error('oh no'))
    }, 1000)
  })
}

function App() {
  const [mutate, {error}] = useMutation(failingMutation)

  async function handleClick() {
    try {
      await mutate()
    } catch (e) {
      // ignore this because useMutation gives me the
      // error that I need to display anyway.
    }
  }

  return (
    <div>
      <div>{error ? error.message : 'no error yet'}</div>
      <button onClick={handleClick}>Click me</button>
    </div>
  )
}

ReactDOM.render(<App />, document.getElementById('root'))
```

The point I'm trying to make here is that there's no value in `useMutation` not handling the rejected promise for us because it gives us the error anyway.

As I was developing this issue, I thought that *maybe* this could be useful for having ErrorBoundaries handle those errors, but then I realized that because the error is happening outside of React's callstack, a failed promise wouldn't get handled by error boundaries anyway. So react-query *could* make that happen and that might be useful, *but* I would argue that it would be better to not, and allow users to just [do this instead](https://codesandbox.io/s/practical-smoke-jzrtu):

```javascript
React.useEffect(() => {
  if (error) throw error
}, [error])
```

Or maybe this could be something as an opt-in option for `useMutation`.

Either way, I think `mutate` needs to not propagate rejected promises. Otherwise we have a bit of unnecessary boilerplate to make sure we don't have unhandled rejections.

What do you think?

**Comment by tannerlinsley** [comment] 2020-02-01 00:39
Hmm I think there are use cases for getting a promise still like in-scope side effects for error handling where you called the mutation. However I would be 100% in on adding an option and global default option that would make these throw or not. That would also make it a backwards compatible change too until we decide to change the default to not throw in the next major version. Thoughts?

**Comment by kentcdodds** [comment] 2020-02-01 00:51
I'm in favor of that 👍

**Comment by tibotiber** [comment] 2020-02-03 05:32
Would love this too. Similar to what I suggested at https://github.com/tannerlinsley/react-query/issues/96#issuecomment-572856758 if I'm getting this right.

**Comment by kentcdodds** [comment] 2020-02-03 14:00
Yes, that's the same thing 👍

**Comment by kentcdodds** [comment] 2020-02-03 14:01
This will be tricky though because if we *also* want people to be able to opt-in to a more Error Boundary friendly situation, then we'll need to tell react-query that we don't want the promise rejected *and* we want the error thrown within React's callstack. Not sure what's best for the names of variables, but in any case I think the current default is something people might want to do, but not as common of a use case.

**Comment by tannerlinsley** [comment] 2020-02-03 14:44
Yeah, that's what I'm thinking. Currently my usage has been gravitating towards handling errors in their own custom hooks (as opposed to in components), and it would be simple enough to just opt-in to a promise being thrown if that's a requirement. Something similar to earlier versions but an opt-in instead of an opt out: `useMutation(mutationFn, { returnPromise: true })` is where my mind is headed.

**Comment by tannerlinsley** [comment] 2020-02-03 14:46
And maybe something like `useMutation(mutationFn, { renderError: true })` for error boundaries? I *think* I can imagine a situation where you would want both a promise returned (for business logic) and the error also rendered to propagate to an error boundary.

**Comment by kentcdodds** [comment] 2020-02-04 15:40
What if this is the API (with these options as defaults eventually)?

```javascript
useMutation(mutationFn, {
  catchRejections: true,
  useErrorBoundary: false,
})
```

I'm thinking the `useErrorBoundary` could default to `false` if you're not using concurrent mode/suspense and default to `true` if you are. Not positive about that. It seems like error boundaries make more sense for queries than mutations 🤔

**Comment by tannerlinsley** [comment] 2020-02-14 19:55
Update: I’ll be getting to this sometime next week. Stay tuned.

**Comment by tannerlinsley** [comment] 2020-02-17 06:06
Released in v0.4.0! Check out the changelog, docs, or this commit for more information: https://github.com/tannerlinsley/react-query/commit/c4bcdac16b0daf19994e055ddd562e89523d3d6e

**Closed by tannerlinsley** 2020-02-17 06:06 UTC

**Comment by TomasRas** [comment] 2020-04-15 06:19
@tannerlinsley I think it would be nice to have the same for manual queries too.

**Comment by devuxer** [comment] 2020-09-06 23:37
I came to this issue because I was following [the docs](https://react-query.tanstack.com/docs/guides/mutations), and my try/catch wasn't catching even though my axios query was definitely failing with a 400 error.

Docs should be updated from `useMutation(pingMutation)` to `useMutation(pingMutation, { throwOnError: true })` (or the example should be changed to now use try/catch). Happy to submit pull request if you let me know which way you'd like to go.

**Comment by Mahdi-Esbati** [comment] 2020-11-05 10:55
###

**Comment by Mahdi-Esbati** [comment] 2020-11-05 10:56
>

**Comment by ievgenk** [comment] 2021-02-23 23:01
> I came to this issue because I was following [the docs](https://react-query.tanstack.com/docs/guides/mutations), and my try/catch wasn't catching even though my axios query was definitely failing with a 400 error.
> 
> Docs should be updated from `useMutation(pingMutation)` to `useMutation(pingMutation, { throwOnError: true })` or the example should be changed to not use try/catch. Happy to submit pull request if you let me know which way you'd like to go.

Yes please if at all possible, amazing library but this def caught me by surprise and brought me here

**Comment by TkDodo** [comment] 2021-02-24 06:31
> Yes please if at all possible, amazing library but this def caught me by surprise and brought me here

this looks pretty outdated. Only .mutateAsync needs try/catch, the example should work as-is

**Comment by ievgenk** [comment] 2021-02-24 19:58
> > Yes please if at all possible, amazing library but this def caught me by surprise and brought me here
> 
> this looks pretty outdated. Only .mutateAsync needs try/catch, the example should work as-is

I see, currently even if I "catch" error in onError of useQuery it still does not prevent error from bubbling to the console. I am probably misunderstadning something... 

`onError: (error) => {
        showErrorMessage(
          error?.response?.data?.message || 'something went wrong',
        )
      },`

**Comment by TkDodo** [comment] 2021-02-24 20:01
That is because react-query logs to the console per default, which you can override: https://react-query.tanstack.com/reference/setLogger

**Comment by ievgenk** [comment] 2021-02-24 22:11
> That is because react-query logs to the console per default, which you can override: https://react-query.tanstack.com/reference/setLogger

Oh wow! Thank you so much @TkDodo for answering and totally helping me out. You are a total gem! 

Maybe it was just me being easily confused, but I feel like adding some of that information to the error-handling page of docs would be great. It seems unlikely to accidentally stumble upon setLogger api page, at least to me.

Again thanks a bunch :)

**Comment by coodoo** [comment] 2022-11-13 01:20
@TkDodo @tannerlinsley 

Seemed `catchRejections` option were not available in the latest version (v4) of `useMutation` and `devtools` still logs `Uncaught promise` message, is there any way to fix this? Thanks.

**Comment by TkDodo** [comment] 2022-11-13 08:06
@coodoo please provide a codesandbox reproduction. `catchRejections` is not something I am familiar with, which means it doesn't exist for at least 2 years 😅.

In v3, the mutation functions were split into `mutate` and `mutateAsync`:
- `mutate` returns nothing and catches errors
- `mutateAsync` returns a Promise, so you need to catch errors manually.

You can read about the differences here: https://tkdodo.eu/blog/mastering-mutations-in-react-query#mutate-or-mutateasync

**Comment by coodoo** [comment] 2022-11-13 08:18
Thanks @TkDodo for the quick reply, `mutateAsync` is exactly the thing I need to manually catch the error instead of letting it showing up in the devtools console! 🙌
