### ISSUE TITLE
`refetch({ throwOnError: true })` returns a promise that never resolves or rejects

### ISSUE THREAD

**Issue by srmagura** [tannerlinsley/react-query#3185] opened 2022-01-12 19:11 UTC
### Describe the bug

Using the `refetch` function returned by `useQuery`, `refetch({ throwOnError: true })` may return a promise that neither resolves nor rejects. I am able to reproduce this problem by calling `refetch` with my internet connection disabled.

### Your minimal, reproducible example

https://codesandbox.io/s/react-query-refetch-throwonerror-j1rbp?file=/src/App.tsx

### Steps to reproduce

The CodeSandbox includes the reproduction steps.

### Expected behavior

The CodeSandbox logs "refetch failed" if you click the refetch button while disconnected from the internet.

### How often does this bug happen?

Every time

### Platform

Google Chrome 97.0.4692.71 on Windows 11

### react-query version

3.34.8

### TypeScript version

4.4.2

**Comment by TkDodo** [comment] 2022-01-14 13:10
this has nothing to do with `throwOnError`. what happens is that react-query internally pauses retries when you are offline. If you set retries to `0`, you will get your error.

Please note that this is one of the behaviours we addressed with v4, where we'll have better support for offline queries.

relevant links:
- https://react-query-alpha.tanstack.com/guides/network-mode
- https://react-query-alpha.tanstack.com/guides/migrating-to-react-query-4#proper-offline-support
- https://github.com/tannerlinsley/react-query/issues/2927

duplicate of:
- https://github.com/tannerlinsley/react-query/issues/2179

**Closed by TkDodo** 2022-01-14 13:10 UTC
