### ISSUE TITLE
Cookies with react-query(next js)

### ISSUE THREAD

**Issue by alisalim17** [tannerlinsley/react-query#2607] opened 2021-08-27 04:15 UTC
Hi, 

i am trying using react-query in next js .But i am using cookies,so i need to put it in the headers.

 ## How can i do that ?

My _app.tsx => 

``` js import Head from "next/head";
import "../styles/globals.css";
import React from "react";
import { QueryClient, QueryClientProvider } from "react-query";
import { Hydrate } from "react-query/hydration";
import { ReactQueryDevtools } from "react-query/devtools";

// import tailwind css file in development for optimizing performance
if (process.env.NODE_ENV === "development") require("../styles/tailwind.css");
else if (process.env.NODE_ENV === "production") require("../styles/prod.css");

const MyApp = ({ Component, pageProps }) => {
  const [queryClient] = React.useState(() => new QueryClient());
  return (
    <QueryClientProvider client={queryClient}>
      <Hydrate state={pageProps.dehydratedState}>
        <Head>
          <meta
            name="viewport"
            content="width=device-width,initial-scale=1,user-scalable=no,user-scalable=0"
          />
        </Head>
        <Component {...pageProps} />
      </Hydrate>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
};

export default MyApp;

``` 

---------------------

When i was using Apollo,i can easily set the headers like this: 

```js import { ApolloClient, InMemoryCache } from "@apollo/client";
import { NextPageContext } from "next";
import { isServer } from "./isServer";
import { withApollo as createWithApollo } from "next-apollo";

const createClient = (ctx: NextPageContext) => {
  console.log("url", process.env.NEXT_PUBLIC_API_URL);
  return new ApolloClient({
    uri: process.env.NEXT_PUBLIC_API_URL,
    credentials: "include",
    headers: {
      cookie: isServer ? ctx?.req?.headers.cookie : undefined,
    },
    cache: new InMemoryCache(),
  });
};

export const withApollo = createWithApollo(createClient);
```

## Then i am able to make queries with headers

```js import React from "react";
import { useMeQuery } from "../../../controller/dist/generated/graphql";
import { withApollo } from "../utils/withApollo";

const Home = () => {
    const { data, loading } = useMeQuery();
  return (
    <div>Hello world</div>
  );
};

export default withApollo({ ssr: true })(Home);
```

# So i am wondering,how can i do same thing with `react-query` ?

**Comment by TkDodo** [comment] 2021-08-29 07:33
duplicate of https://github.com/tannerlinsley/react-query/discussions/2606

**Closed by TkDodo** 2021-08-29 07:33 UTC
