### ISSUE TITLE
rejected promises triggered by devtools causes crash

### ISSUE THREAD

**Issue by yinghaochan** [tannerlinsley/react-query#2014] opened 2021-03-23 20:01 UTC
**Describe the bug**
If there's a  query which throws, usually `const { status, data, error } = useQuery(...)` one would just use `error` and render the error in jsx

However, if that throw is the result of clicking refetch in the devtools, the entire app crashes (see screenshot)

**To Reproduce**
https://codesandbox.io/s/strange-drake-9dyow?resolutionWidth=320&resolutionHeight=675&file=/pages/index.js
1. Open the repro demo in browser
2. wait for a auto refetch to fail (it fails 50% of the time)
3. See the page change
4. hit refetch in devtools until it fails
5. app crashes
6. 
**Expected behavior**
App does not explode :P

**Screenshots**
when rejected naturally:
![image](https://user-images.githubusercontent.com/7133601/112209905-3f3b1c00-8bd7-11eb-8f3c-385661635191.png)
When 'refetched' by devtools:
![image](https://user-images.githubusercontent.com/7133601/112209844-2cc0e280-8bd7-11eb-9e3b-1bccf91ea3b6.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: canary

**Comment by TkDodo** [comment] 2021-03-23 20:10
confirmed. seems like a good first issue since a fix would be non-production impacting. do you want to give it a shot?

**Comment by yinghaochan** [comment] 2021-03-23 20:48
Thanks for the quick response!
I could get to fixing it in a week or so, if no one else has worked on it by then.

**Comment by TkDodo** [comment] 2021-03-23 21:08
sounds good 👍

**Comment by prateek3255** [comment] 2021-06-05 07:26
Hey @TkDodo, I opened a fix for this issue with #2344

**Closed** 2021-06-05 08:53 UTC
Labels: bug, devtools
