### ISSUE TITLE
Manual Query page search result leads to 40

### ISSUE THREAD

**Issue by rickvian** [tannerlinsley/react-query#2958] opened 2021-11-17 03:30 UTC
**Describe the bug**
when searching for `manual query`, clicking first result will lead to docs url below , but its 404
https://react-query-v2.tanstack.com/guides/parallel-queries#manual-parallel-queries

**To Reproduce**
1. Go to https://react-query-v2.tanstack.com/
2. Click on search bar, input `manual query` select first result
3. See error

**Expected behavior**
not 404

**Screenshots**
![Image 1731](https://user-images.githubusercontent.com/8034141/142129583-51237de8-f193-4a1d-baf4-3c971f751351.jpg)

**Comment by TkDodo** [comment] 2021-11-17 07:00
This is the 5th issue duplicate of this, please use the issue search before opening a new one: https://github.com/tannerlinsley/react-query/issues/2136

**Closed by TkDodo** 2021-11-17 07:00 UTC
