### ISSUE TITLE
Second query in dependent query outputs `status - "success"` before fetching

### ISSUE THREAD

**Issue by navin-moorthy** [tannerlinsley/react-query#526] opened 2020-05-28 08:49 UTC
### Subject of the issue

Issue in dependent query fetching,

Even before the second query starts fetching, the status - `success` is returned

### My environment

* version of react-query - 1.5.3
* version of next-js - 9.4.2

### Steps to reproduce

Issue reproduced in codesandbox - https://codesandbox.io/s/react-query-doubts-j3fhh

### Expected behaviour

Second Query should be returning status - `loading` till the `isFetching` is done.

### Actual behaviour

![react-query-issue](https://user-images.githubusercontent.com/39694575/83117842-37136c80-a0eb-11ea-99f7-2412340e3efc.gif)

### Note:

I can directly **`await` for the both the query in the same useQuery**, but in my use-case, I have to useQuery to fetch primary data and with the above fetched data as dependency for useInfiniteQuery to get the final data. In the end, I need both primary data and the final data.

Also I cannot **`await` for both the query inside useInfiniteQuery**, because I need the data from both the query to be availabe in the resulted data. 

But useInfiniteQuery returns an array which becomes hard to get the data from first query. 

Also I see that **useInfiniteQuery calls the fetchFunction twice during the initial page load** during my experiment.

**Comment by denisborovikov** [comment] 2020-05-28 21:42
Looks like a duplicate of #280

**Comment by tannerlinsley** [comment] 2020-06-02 04:56
Indeed. even with this new issue, my response remains the same. This is something we will have to address in future major (breaking) versions of the library.

**Closed by tannerlinsley** 2020-06-02 04:56 UTC

**Comment by navin-moorthy** [comment] 2020-06-09 06:52
> Indeed. even with this new issue, my response remains the same. This is something we will have to address in future major (breaking) versions of the library.

Great! Thanks, I will continue using the workaround as of now.
