### ISSUE TITLE
Side effects in useQuery function or outside of useQuery in a useEffect?

### ISSUE THREAD

**Issue by shamilovtim** [tannerlinsley/react-query#1938] opened 2021-03-10 18:13 UTC
**Describe the bug**
Do the author or the contributors of this library have any opinions on the presence of side effects in the useQuery function, or should side effects be outside of useQuery in a useEffect of a custom hook?

The [Queries docs page](https://react-query.tanstack.com/guides/query-functions) does not seem to take a stance on this and the rest of the docs don't come up with any opinions. Curious about your experiences and any pros / cons. Thanks!

**Comment by TkDodo** [comment] 2021-03-10 18:38
The queryFn should be pure imo, you can trigger side effects in the onSuccess / onError / onSettled callbacks or in dedicated effects. Which side effects are we talking about?

moving this to discussions as it’s not a bug.

**Closed** 2021-03-10 18:38 UTC
