### ISSUE TITLE
useQueries returns new array on every call (even if queries have not changed)

### ISSUE THREAD

**Issue by bman654** [tannerlinsley/react-query#1973] opened 2021-03-15 20:55 UTC
**Describe the bug**
I have a project using 3.8.3 with code like the following:

```jsx
function Component() {
  const [mystate, setMystate] = React.useState(0);
  const results = useQueries([
    { queryKey: ["foo", "bar"], queryFn: () => Promise.resolve(42)},
  ]);
  
  React.useEffect(() => {
    // trigger some other state change whenever our query results change
    setMystate(mystate + 1);
  }, [results]);
  
  return <div>.</div>;
}
```

This code runs fine in 3.8.3.  The component re-renders when you would expect (when the query status changes or when we change state).

But if I run the same code in 3.12.1 the component enters an infinite re-render loop.

**To Reproduce**
Here is a repro in codepen: https://codepen.io/bman654/pen/NWbmxWe?editors=0012

* open the Console and you'll see it re-renders 502 times (basically until the effect short-circuits itself)
* edit the imports and the top and comment out the import of 3.12.1 and uncomment 3.8.3 and now the component only renders twice (expected behavior)

**Expected behavior**
useQueries() should return the same array instance if the queries have not changed (and their status has not changed)

**Additional context**
I traced this issue to the 3.9.0 release.  [This diff](https://github.com/tannerlinsley/react-query/compare/v3.8.3...v3.9.0#diff-d1b1d4e3c1d5b653533620a0b77d0873a170c747a9bd5ae5db7d58f8606262d0) has the changes.

I traced the issue to this:
* `useQueries` now calls `getOptimisticResult` to get the result to return to the calling component
* `getOptimisticResult` (a new function in this changeset) always returns `queries.map(...)` guaranteeing that it will return a new array instance every time.

**Comment by TkDodo** [comment] 2021-03-15 21:12
duplicate of https://github.com/tannerlinsley/react-query/issues/1905

**Closed by TkDodo** 2021-03-15 21:12 UTC
