### ISSUE TITLE
A query remains indefinitely in "fetching" status when the component where it is originated crashes

### ISSUE THREAD

**Issue by ingro** [tannerlinsley/react-query#1182] opened 2020-10-19 09:08 UTC
**Describe the bug**
A query remains indefinitely in "fetching" status when the component where it is originated crashes and the error is catched by an error boundary.

**To Reproduce**
I've created a codesandbox to show the bug, you can see it here: https://codesandbox.io/s/loving-grothendieck-5ovgm
1. Go to the codesanbox;
2. Click on "Show Posts"
3. Close the error overlay, you can see that the global fetching indicator shows that 1 query is still running, and if you open the devtools you can see the query in "fetching" status
4. You could then go back to the home and then click to the "todos" list, it works as expected but the global fetching indicator still remains to 1 after the fetch is completed

**Expected behavior**
The query originated in the crashed component should not hang and be removed from the query cache.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 86

**Comment by tannerlinsley** [comment] 2020-11-03 20:56
Hmmm. It looks like a bug for sure.

**Comment by dominictwlee** [comment] 2020-11-04 21:47
Happy to look into this.

**Comment by tannerlinsley** [comment] 2020-11-04 23:49
Awesome!

**Comment by dominictwlee** [comment] 2020-11-05 17:26
![image](https://user-images.githubusercontent.com/34794189/98273827-9c1c9980-1f8a-11eb-8b05-2e46ec4fde70.png)
 
On first glance, this bit seems to be the culprit. 
Because the default `isFetching` state is true if enabled when Query is instantiated, if an error is thrown before fetch has a chance to be called, then this will stay true.

I'm assuming that there is some important reason why it defaults to 'isFetching` true on `getDefaultState` given that a few tests broke if that condition is removed from the ternary.

Any thoughts on how we would like to proceed with this?

**Comment by tannerlinsley** [comment] 2020-11-05 18:33
I believe it's true to avoid rendering for a split second with `idle`, then immediately switching to a loading state after mount. My guess is that should probably stay the way it is and instead, we should investigate a way to detect the error and set it to the appropriate state.

**Comment by boschni** [comment] 2020-11-05 20:35
Seems to be fixed in V3: https://codesandbox.io/s/eager-montalcini-gn3s4

**Comment by tannerlinsley** [comment] 2020-11-06 01:11
Sweet! Let’s close this then since these features are still considered experimental.

**Closed by tannerlinsley** 2020-11-06 01:11 UTC
Labels: bug, good first issue, suspense

**Comment by sumeet030990** [comment] 2022-04-13 17:32
facing same issue, any fix?

**Comment by TkDodo** [comment] 2022-04-13 20:35
@sumeet030990 please open a new issue with a minimal reproduction, thanks.
