### ISSUE TITLE
The type for `useQueries` is not genertic

### ISSUE THREAD

**Issue by jcready** [tannerlinsley/react-query#2562] opened 2021-08-11 16:11 UTC
**Describe the bug**
When a value with a concrete `UseQueryOptions` type is passed to `useQueries()` the resultant `data` type is `unknown` instead of being the `TData` type argument from the `UseQueryOptions` type. The type for `useQueries` should be generic just like the type for `useQuery`.

**To Reproduce**
```ts
import { useQuery, useQueries, UseQueryResult, QueryFunction, UseQueryOptions } from 'react-query';

export const KEY = 'test';
export type Key = typeof KEY;

export type Result = string;
export type QueryKey = [
    Key,
    {
        id: string;
    }
];

export type QueryOptions = UseQueryOptions<Result, unknown, Result, QueryKey>;
export type QueryResult = UseQueryResult<Result>;

export const queryFn: QueryFunction<Result, QueryKey> = ({ queryKey: [, { id }] }) => id;

export function getQueryOptions(id: string): UseQueryOptions<Result, unknown, Result, QueryKey> {
    return {
        queryKey: [KEY, { id }],
        queryFn,
    };
}

export function useTestResult(id: string): QueryResult {
    return useQuery(getQueryOptions(id));
}

export function useTestResults(ids: string[]): QueryResult[] {
    return useQueries(
        ids.map((id) =>
            getQueryOptions(id)
        )
    );
}
```

**Expected behavior**
No type errors.

**Actual behavior**
Type error for `useQueries()` usage:
```
Type 'UseQueryResult<unknown, unknown>[]' is not assignable to type 'QueryResult[]'.
  Type 'UseQueryResult<unknown, unknown>' is not assignable to type 'QueryResult'.
    Type 'QueryObserverIdleResult<unknown, unknown>' is not assignable to type 'QueryResult'.
      Type 'QueryObserverIdleResult<unknown, unknown>' is not assignable to type 'QueryObserverIdleResult<string, unknown>'.
        Type 'unknown' is not assignable to type 'string'. ts(2322)
```

**Comment by TkDodo** [comment] 2021-08-11 17:17
Duplicate of https://github.com/tannerlinsley/react-query/issues/1675

**Closed by TkDodo** 2021-08-11 17:17 UTC
