### ISSUE TITLE
Dynamic parameters  in useMutation

### ISSUE THREAD

**Issue by adeepika1991** [tannerlinsley/react-query#1337] opened 2020-11-30 15:59 UTC
I would like to reuse my fetch function inside useMutation  hook in different places in my react app.  Each fetch function has different url endpoints and data. While I can pass data inside mutate function, how do I pass other parameters like url, http methods ? 

I tried passing url parameter, I am getting
`index.js:1 SyntaxError: Unexpected token W in JSON at position 0`

My fetch function is as follows
```
const postPhone = async (data, url) => {
    const requestOptions = {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data)
    };
    const response = await fetch(
       permanentUrl + url ,
        requestOptions
    );

    const otpResponse = await response.json();
    return otpResponse;

}
```

If I have to use a static url inside the function with no url parameter then mutate function of useMutation is working absolutely fine. But then I have to write multiple postPhone function many times. Is there any solution for this?

**Comment by TkDodo** [comment] 2020-12-02 10:41
`useMutation` only takes one parameter for `variables`. Please see this discussion: https://github.com/tannerlinsley/react-query/discussions/1226

**Comment by tannerlinsley** [comment] 2020-12-07 06:16
Duplicate of #1322

**Closed by tannerlinsley** 2020-12-07 06:16 UTC
