### ISSUE TITLE
`prefetchQuery` gets called on 'valid' data

### ISSUE THREAD

**Issue by ricardozv28** [tannerlinsley/react-query#2716] opened 2021-09-24 17:01 UTC
**Describe the bug**
As described in #2560, invoking `prefetchQuery` will request data even when the data is still 'valid' by passing a staleTime to `useQuery`, in my case I have a 'useEffect' that will get fire every time my 'items' list change, it will prefetch data that the user will use in the workflow of the app. 

**To Reproduce**
I created a quick reproducible example
1. Go to https://codesandbox.io/s/react-query-prefetch-dnlmd?file=/src/index.js
2. Make sure react-query devtool is open
3. Click on `updateCache` button
4. See how the individual `post` queries are getting fetched even when the queries are still 'valid'

**Expected behavior**
As described in the docs: 
> If data for this query is already in the cache and not invalidated, the data will not be fetched

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  94.0.4606.54

**Comment by TkDodo** [comment] 2021-09-25 10:16
Thanks for the reproduction, but please see [the docs on prefetching](https://react-query.tanstack.com/guides/prefetching):

> If a staleTime is passed eg. prefetchQuery('todos', fn, { staleTime: 5000 }) and the data is older than the specified staleTime, the query will be fetched

So all you need to do is pass `{ staleTime: 180000 }` to `prefetchQuery` to avoid those fetches. Here is a fork of your sandbox showing that it works: https://codesandbox.io/s/react-query-prefetch-forked-bd5hu?file=/src/index.js:3410-3431

**Comment by ricardozv28** [comment] 2021-09-27 16:57
but that kinda contradicts the first bullet point

> If data for this query is already in the cache and not invalidated, _**the data will not be fetched**_

we should not need to provide a staleTime if the data is still marked as valid.

**Comment by TkDodo** [comment] 2021-09-28 20:42
seems like there is a bit of a misunderstanding here:

1) you prefetch queries for single post entries (1-100). Those queries have no observer yet, so they are inactive. They also have _no staleTime_, because no observer has been mounted. So there is no way to consolidate the staleTime that you might set when the `Post` component mounts.
2) Even if you e.g. were to prefetch a query that has a currently mounted observer, you would still have to either pass staleTime to prefetchQuery _or_ set a default staleTime for your key via `queryClient.setQueryDefaults` for it to be picked up. The reason seems to be that `staleTime` is a per-observer option.

I think 1) is very much expected and not much we can do

Regarding 2), I'm not sure tbh. Here is a very minimalistic reproduction  of just prefetching an active query that has an infinite staleTime, and it always refetches: https://codesandbox.io/s/react-query-prefetch-forked-zzm0d?file=/src/index.js

So at least we should update the docs, or we could look at all observer and take their options into account, but I don't think that was intended.

@tannerlinsley what do you think please?

**Comment by ricardozv28** [comment] 2021-10-07 21:47
as you point into the minimalistic reproduction, so even if the item is set to Infinity, the `prefetch` always fetch the data, so I wonder if the `prefetch` functionality should change and only acts when there is no data stored in the cache, that way we won't need to pass a stale time or look for the observers

the main issue that I was running into was a 'race condition' where the `useEffect()` that I am using for prefetching was getting trigger because an `optimistic` update using `useMutation`  changes the data in the `onMutate` and the prefetch got called before the data actually updates in the server, then when `onSettled` gets called to `refetch` the recently updated data, the request didn't happen since it was triggered by the `prefetch` query, and the UI got 'reverted' to the old data

**Comment by TkDodo** [comment] 2021-10-08 14:32
> that I don't quite understand. Even if a prefetching is in-flight, if you call invalidateQueries, it should still fire another request, should it not?

ah, I think that might be wrong. If we're already fetching, there won't be another request. I think you could either:
- call `cancelQueries` before calling `invalidateQueries`
- not `prefetch` for an optimistic update
- pass `staleTime` to prefetch

**Comment by TkDodo** [comment] 2021-10-30 18:29
also, `invalidateQueries` now has a handy `cancelRefetch` option that you can use to make sure that any currently outgoing request is cancelled so that `invalidateQueries` really fires off a request.

Is there anything else you should think we could do, or can we close this issue?

**Comment by ricardozv28** [comment] 2021-11-01 14:56
maybe we can add something more specific into the 'prefetch' docs to make it clear that we need to pass a staleTime if we don't want `prefetch` to request the data again, right now the docs make it sound it is one or the other:

> * If data for this query is already in the cache and not invalidated, the data will not be fetched
> * If a staleTime is passed eg. prefetchQuery('todos', fn, { staleTime: 5000 }) and the data is older than the specified staleTime, the query will be fetched

**Comment by TkDodo** [comment] 2021-11-01 15:20
That’s a good idea. Please feel free to make a PR that updates the docs

**Comment by tobias-tengler** [comment] 2021-11-15 07:45
I'm having a similar problem. I execute the prefetch in a mouseOver event (which is potentially called often) and I'm seeing it executing a network call every time.
I've tried playing around with the `cacheTime` and `staleTime` without success. The query is only used once the client actually clicks on the thing the mouseOver event is on. I'm also using a queryKey that's an array.

```ts
export function prefetchMachine(queryClient: QueryClient, machineId: string) {
    return queryClient.prefetchQuery(['machine', machineId], () => fetchMachine(machineId), {
        staleTime: 1000 * 60 * 60,
        cacheTime: 1000 * 60 * 60,
    });
}
```

**Comment by TkDodo** [comment] 2021-11-15 08:23
@tobias-tengler hmmm, interesting. I'd expect multiple calls to `prefetchQuery` with that configuration to only yield one request per `staleTime`. Can you create a codesandbox reproduction for that please?

**Comment by TkDodo** [comment] 2021-12-10 21:44
> also, invalidateQueries now has a handy cancelRefetch option that you can use to make sure that any currently outgoing request is cancelled so that invalidateQueries really fires off a request.

This setting will also be the default in v4. Feel free to re-open the issue with a reproduction.

**Closed by TkDodo** 2021-12-10 21:44 UTC
