### ISSUE TITLE
Explode useQueryClient losing this reference

### ISSUE THREAD

**Issue by lrdass** [tannerlinsley/react-query#1575] opened 2021-01-05 14:07 UTC
**Describe the bug**
explode `const {invalidateQuery} = useQueryClient()` makes the `invalidateQuery` lose `this` context

**To Reproduce**
`const {invalidateQuery} = useQueryClient()`
`invalidateQuery()`
https://codesandbox.io/s/clever-keldysh-704g7?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js

**Expected behavior**
If exploded the `useQueryClient`  object, invalidateQuery should not lost `this` reference

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Firefox
 - Version: Latest

**Comment by amed** [comment] 2021-02-26 08:57
This is confirmed also on the latest version (3.11.0)

`const { invalidateQueries } = useQueryClient()` => ` invalidateQueries()` 

throws an issue related to:

```
TypeError: Cannot read property 'queryCache' of undefined
```



The fix is by calling:
```
  const queryCache = useQueryClient()
  queryCache.invalidateQueries()
```

My guess it that this issue is also related to the lost context.

**Comment by stiaanj** [comment] 2021-03-17 05:57
I also ran into this issue this morning. Was staring at the docs: "What am I doing wrong here?" Thanks for raising this issue.

**Comment by TkDodo** [comment] 2021-06-04 19:40
gonna close this issue since the linked PR was also closed some time ago.

**Closed by TkDodo** 2021-06-04 19:40 UTC
Labels: bug, merge pending

**Comment by atsikov** [comment] 2021-06-10 10:48
Looks like it was not fully fixed. I still have the same error with `refetchQueries` in `react-query@3.16.1`.
https://codesandbox.io/s/vigilant-wozniak-xrf3x?file=/src/index.js

**Comment by TkDodo** [comment] 2021-06-10 10:56
it wasn't fix, but see the explanation here on why the fix wasn't merged: https://github.com/tannerlinsley/react-query/pull/1586#issuecomment-810909822

**Comment by Justinohallo** [comment] 2021-08-30 21:42
Is there somewhere in the Docs that describes this limitation? I spent an hour or so trying to debug this, not even thinking about destructuring being an issue.

**Comment by TkDodo** [comment] 2023-04-28 14:58
> Still an issue as of v4.29 in April 2023

Because even in April 2023, the `QueryClient` is still a `class`, and that's how classes work in JavaScript. You know the `QueryClient` is a class because you create it with `new QueryClient()`:

```
const queryClient = new QueryClient()
```

Have you ever tried this?

```
const { getDay } = new Date()

getDay()
```

instead of `new Date().getDay()` ?

It will blow up just the same...

**Comment by ouifi** [comment] 2023-04-28 15:01
> 

Implementation details should be completely transparent to library consumers. 

In almost every other hook in the React ecosystem, you can destructure the properties/methods you want from the hook return value. 

At the very least, if it wont be fixed, it should be called out in the documentation that you *cant* do this, because it breaks from a very popular convention in the react ecosystem.

**Comment by apperside** [comment] 2023-10-03 07:12
I got crazy trying to understand why I was getting this silly error, and the problem what that I was destructuring the query client, wtf!

**Comment by amosmachora** [comment] 2024-01-16 09:07
I love it when i find out people face the same error as me 😂😂😂

**Comment by TkDodo** [comment] 2024-01-16 09:13
If you think this is something that needs documenting - please open a PR to the docs. I for one don't think it's necessary - we're also not documenting that you cannot use hooks in class components, because it's not query specific. Same here - this is pure javascript runtime behaviour for all classes. If our docs need to educate people on how classes in js work, okay, please add it. No one has made a PR in the 3 years since this issue was opened though :)

**Comment by amosmachora** [comment] 2024-01-16 09:38
While you are here im going to ask a stupid noob question, is there a difference between exporting the queryClient from a certain file and using it across my app and using the useQueryHook?

Out of scope but I would love to learn

`  const queryClient = useQueryClient();
`

and 

`export const queryClient = new QueryClient();
`

**Comment by TkDodo** [comment] 2024-01-16 12:35
see: https://tkdodo.eu/blog/react-query-fa-qs#why-should-i-usequeryclient
