### ISSUE TITLE
Add a setting to refetch on navigational focus if onError is reached

### ISSUE THREAD

**Issue by shamilovtim** [tannerlinsley/react-query#2208] opened 2021-04-28 20:41 UTC
Currently, there exists the following common state in React Query:
- A query fails
- The retries are unsuccessful 
- The useQueries throw `onError` and are no longer ever functional because the screens they are on stay mounted.

If and when those queries could potentially succeed again, there is no way to make them run again without a lot of manual effort and redevelopment. Instead ideally there would be a setting called `ifErrorFetchOnFocus`. What we want is if the state of the query is `Error` then when the screen the query is mounted on gets focused (or if the query is re-mounted), it attempts a retry. Actually if we had this setting, we would probably not use manual retries at all. Instead we'd let a query error on the first try, and let the user re-trigger it by simply focusing the screen again.

EDIT: Just a clarification that what I'm describing is **navigational refocus** via React Navigation, which React Query doesn't account for. It is in fact true that React Query refetches when the window is backgrounded and maximized but it doesn't refetch on navigational focus.  I'm not sure if this is equally a problem on web but I would assume so, given that React Query doesn't seem to ever know that a navigational refocus occurred.

**Comment by tannerlinsley** [comment] 2021-05-11 20:49
In the case that there is no error, does it refetch on navigation when you expect it to?

**Comment by shamilovtim** [comment] 2021-05-11 20:54
> In the case that there is no error, does it refetch on navigation when you expect it to?

Only if we hardcode each particular screen to refresh on focus imperatively outside the library using `useFocusEffect()` and then triggering `refetch` on the individual query. I had to build a convenience hook for this, attached below. However, the reason I opened this ticket is because I figured you might want this in the library, given that refetching on navigation is a common use case, along with refetching on navigation if there is an error.

Additionally `refetch` sort of feels dirty to use like this, but it didn't seem like I had any other options.

```typescript
import { useCallback, useEffect, useRef } from 'react';
import { useFocusEffect } from 'react-navigation-hooks';
import { UseQueryResult } from 'react-query';

export const useFetchQueryOnRefocus = (query: UseQueryResult) => {
  const isMountedRef = useRef(false);

  useFocusEffect(
    useCallback(() => {
      // do not refetch when query is initially mounted
      if (isMountedRef.current) {
        query.refetch();
      }
    }, [query.refetch])
  );

  useEffect(() => {
    isMountedRef.current = true;
  }, []);
};
```

**Comment by tannerlinsley** [comment] 2021-05-11 20:57
Gotcha. The issue is clear to me now, however the solution is going to need some R&D for sure. What we really need is a sandbox that sets up this flow/experience as it is today. From there, I think I can get a better feel for how to move forward.

**Comment by TkDodo** [comment] 2021-05-12 05:12
> You can reproduce this issue by using react router or react navigation and, after an error, navigating between screens which do not dismount. You will see that react query never refreshes its queries after an error.

oftentimes, navigation goes hand in hand with a remount, e.g. when I go from /profile to /dashboard or so. But I agree, not always. For example, when I go from /todo/1 to /todo/5, the TodoDetails component is mounted and stays mounted. But, we are seeing a different id here, which should be part of the queryKey, which will trigger a refetch because the query key changes. 

So what would be an example that includes navigation without mounting where you would trigger the exact same query without a change in query key please?

**Comment by shamilovtim** [comment] 2021-05-12 22:17
I'll try to get a reproducible example. A simple [bottom tab navigator](https://reactnavigation.org/assets/navigators/tabs/material-bottom-tabs.gif) is the best example of this failure because bottom tabs stay mounted at all times and do not dismount. Thus any queries failing in the root screen of a bottom tab navigator will not be refetched.

**Comment by TkDodo** [comment] 2021-05-30 12:39
> I'll try to get a reproducible example. A simple bottom tab navigator with each tab having a scren is the best example of this failure because bottom tabs stay mounted at all times and do not dismount. Thus any queries failing in the root screen of a bottom tab navigator will not be refetched.

in this example, wouldn't each screen have it's own query? like, when you click on `album`, the album screen mounts and fetches albums, and when clicking on `library`, the album screen unmounts and the library screen mounts and fetches libraries?

if you have a query _in_ the navigation bar that gives you e.g. the items of the navigation bar, then I'm not sure how you can navigate to / away from this screen? Here, I would probably just render an error boundary with a `retry` button to let the user retry the query.

**Comment by shamilovtim** [comment] 2021-06-01 20:51
> > I'll try to get a reproducible example. A simple bottom tab navigator with each tab having a scren is the best example of this failure because bottom tabs stay mounted at all times and do not dismount. Thus any queries failing in the root screen of a bottom tab navigator will not be refetched.
> 
> in this example, wouldn't each screen have it's own query? like, when you click on `album`, the album screen mounts and fetches albums, and when clicking on `library`, the album screen unmounts and the library screen mounts and fetches libraries?
> 
> if you have a query _in_ the navigation bar that gives you e.g. the items of the navigation bar, then I'm not sure how you can navigate to / away from this screen? Here, I would probably just render an error boundary with a `retry` button to let the user retry the query.

In most navigational libraries many screens do not dismount. For instance, a screen mounted earlier in a stack will not dismount as you go farther in a stack. Bottom tabs are also an example of this, these screens stay mounted. So React Query would never have a chance to do what it needs to.

**Comment by TkDodo** [comment] 2021-06-02 05:20
> In most navigational libraries many screens do not dismount. 

Don't know about react-native, but react-router for example doesn't do this ... there is only one screen rendered and mounted at the same time as far as I know ...

> For instance, a screen mounted earlier in a stack will not dismount as you go farther in a stack. Bottom tabs are also an example of this, these screens stay mounted. So React Query would never have a chance to do what it needs to.

not sure if that is tied to `navigation` ... it seems like you want hidden components to do something when you visually show them? This doesn't seem like something react-query could take care of, maybe toggling manually with the `enabled` prop would work. If you instantly mount 4 screens and have 3 in a hidden state, how would react-query know which one is the "active" one?

ModalDialogs can have the same issue, if you just render them in closed state. I've moved away from this approach for various reasons - effects being run on mount is one of them, but also perf. It means that all hidden dialogs are always rendered / rerendered and on a dashboard with 20 widgets, each having a dialog, this was expensive.

**Comment by TkDodo** [comment] 2021-06-27 12:43
closing again due to staleness. Feel free to reopen with a reproduction.

**Closed by TkDodo** 2021-06-27 12:43 UTC

**Comment by shamilovtim** [comment] 2021-06-27 18:45
I'll try to get a repro soon

**Comment by kylebake** [comment] 2021-10-05 16:16
> Don't know about react-native, but react-router for example doesn't do this ... there is only one screen rendered and mounted at the same time as far as I know ...

React-navigation doesn't operate like this. See: https://reactnavigation.org/docs/navigation-lifecycle/

In the case of the bottom tab navigator in react-navigation, none of the top level tab screens are unmounted when navigating between the tabs, they're all mounted all the time until you navigate back away from the tab navigation. 

I was able to get a workaround going in our app using the `useIsFocused` hook with the `enabled` property in `useQuery`. I could post the solution if there's interest.

**Comment by TkDodo** [comment] 2021-10-05 17:34
> I was able to get a workaround going in our app using the useIsFocused hook with the enabled property in useQuery. I could post the solution if there's interest.

that’s what i was thinking as well: somehow find out which tab is active and only enable the query on the current tab. You’ll also get an automatic refetch when enabled changes 👍
