### ISSUE TITLE
Cannot use a hook (like useQuery) inside a function component that will be rendered in a class component. [ERROR:  Object(...) is not a function]

### ISSUE THREAD

**Issue by Danscap** [tannerlinsley/react-query#842] opened 2020-08-07 00:35 UTC
I am using react v16.8.0
and react dom v16.8.0

react-query v2.5.13

I created an Avatar component. see below

![image](https://user-images.githubusercontent.com/34867523/89596166-7d402700-d824-11ea-9525-af64a47b25e5.png)

I attempt to render this inside a class component ( <Avatar  ... />

![image](https://user-images.githubusercontent.com/34867523/89595919-e4a9a700-d823-11ea-8fdb-d133ed91c35f.png)

I receive this error. 

![image](https://user-images.githubusercontent.com/34867523/89595959-0440cf80-d824-11ea-9536-e0ce00d2f066.png)

I have tried using other hooks such as useState, so I know it isn't that it isn't hooks in general that is the issue. It seems to just be react-query hooks.

Is this library just not compatible with class components, or am I implementing them wrong?

Please advise.

**Comment by lgenzelis** [comment] 2020-08-08 02:36
@Danscap could you try to reproduce this with a MWE in [CodeSandbox](http://codesandbox.io/)?  I don't see what could be the issue. 

Note: I'm not a maintainer.

**Comment by Danscap** [comment] 2020-08-08 13:50
It will be difficult as I changed the code to not use react-query and added a lot more logic.

My code base is primarily class components.

I was wondering if someone could provide an example of a working function using react query hooks that could be successfully added into a class component. I would like to see what the difference is between that and my code so I could implement it in the future.

**Comment by razh** [comment] 2020-08-08 19:24
react-query works with function components inside class components.

How are you importing `<Avatar>`? This may be an import issue. `TypeError: Object(...) is not a function` is generally seen with incorrect imports:

https://www.google.com/search?q=TypeError%3A+Object(...)+is+not+a+function+react

```tsx
// Named export
import { Avatar } from './path/to/Avatar;

// Default export
import Avatar from './path/to/Avatar;
```

Otherwise, does updating React work in your case?

**Comment by Danscap** [comment] 2020-08-08 22:52
Avatar was the only component in that js file so I was exporting it as default and importing without brackets as you explained.

That wasn't the issue.

I'm not sure why specifically react-query hooks do not work. I know that hooks require react and react-dom v16.8.0 or higher, which I have. As I mentioned I also tested other hooks and they do work.

**Comment by krashdifferent** [comment] 2020-08-12 17:45
I think your issue may lie outside react-query and the useQuery hook. Here is a code sandbox showing useQuery in a functional component used by a class component: [https://codesandbox.io/s/boring-hopper-8mbv3?file=/src/App.js](url)

**Comment by tannerlinsley** [comment] 2020-08-20 17:07
This looks like it has nothing to do with RQ, but more of a general react question. Closing for now.

**Closed by tannerlinsley** 2020-08-20 17:07 UTC
