### ISSUE TITLE
Hits API twice for v2.26.3

### ISSUE THREAD

**Issue by NiketMalik** [tannerlinsley/react-query#1306] opened 2020-11-20 10:01 UTC
**Describe the bug**
Any query using `useInfiniteQuery` hook when cleared and refetched fires API twice.

**To Reproduce**
```js
clear();
refetch();
```

This issue is only present in v2.6.3 and 2.6.2(have tested only these 2)

**Sandbox Replication**
https://codesandbox.io/s/silent-cache-no9tj?file=/pages/index.js

----------------
EDIT: As pointed by @peterkrieg the version I have tested for are v2.26.3 and 2.26.2

**Comment by peterkrieg** [comment] 2020-11-23 01:39
I'm also noticing this, with the `usePaginatedQuery` hook, with react-query `2.23.0`

**Comment by peterkrieg** [comment] 2020-11-30 16:06
I believe this has been fixed in react-query v3.  I made a codesandbox of the original, just with updating react-query to `3.2.0-beta` and fixing the necessary renamed imports/functions.  

https://codesandbox.io/s/heuristic-colden-foksn?file=/pages/index.js

@NiketMalik  do you mind taking a look at that and verifying your example works as expected?  (I no longer see 2 requests being made in the network in devtools).  

I would update to react-query v3, but not sure when the release from beta is expected (and if there are any of breaking changes still coming in v3).  Still will probably upgrade soon either way.

**Comment by NiketMalik** [comment] 2020-12-01 09:09
> I would update to react-query v3, but not sure when the release from beta is expected (and if there are any of breaking changes still coming in v3). Still will probably upgrade soon either way.

This is the main issue, we would have upgraded to v3 if it was production ready.

**Comment by tannerlinsley** [comment] 2020-12-07 04:37
v3 is launching as soon as possible, so feel free to upgrade any time!

**Closed by tannerlinsley** 2020-12-07 04:37 UTC

**Comment by DaleyKD** [comment] 2020-12-10 19:28
OH MY GOODNESS!!  I've been beating my head against a wall **all day**, trying to figure out why my API was being called 3 times.  I knew it was being re-rendered numerous times due to a bug in a different npm package (currently waiting a fix), but I thought RQ would have handled it.

Upgraded to v3.2.0-beta.35 and it seems to have went away.  THANK. YOU.

I hope this is GA before the end of our current Program Increment. :)

**Comment by mrlubos** [comment] 2020-12-28 08:59
@tannerlinsley I am facing an issue that sounds related to this, but it appears to be caused by token refresh when a call throws 401. Somehow, react-query ends up calling the same failing query twice, leading to downstream effects. Most notably, my cached data for this query gets flushed which is the real problem in my case. Have you heard of this issue before? Do you know if upgrading to v3 might help? It's hard to debug in my application as is, don't think I am able to provide a reproducible example at this time, sorry!
