### ISSUE TITLE
Disabled requests are executed after cache invalidation

### ISSUE THREAD

**Issue by av1at0r** [tannerlinsley/react-query#648] opened 2020-06-28 11:04 UTC
**Describe the bug**
Disabled requests are executed after cache invalidation

**To Reproduce**
1 Use useQuery hook with the ```"items"``` key and pass ```{enabled: false}``` to the settings
2. Call ```queryCache.invalidateQueries("items")```
3. The request will be fulfilled despite ```{enabled: false}```

**Expected behavior**
The request will not be executed after the cache is invalidated, because in its settings it is  ```{enabled: false}```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 83
 - Version 2.4.2

**Additional context**
[Sandbox](https://codesandbox.io/s/react-query-bug-df2gg)

**Comment by GuillaumeSpera** [comment] 2020-06-28 13:29
Hi there, might me a duplicate of my issue #635. If so, it has been fixed in new release

**Comment by av1at0r** [comment] 2020-06-28 15:00
The bug is still reproduced in version 2.4.2

**Comment by GuillaumeSpera** [comment] 2020-06-28 15:02
Yep, you are right. My issue is also still reproduced in version 2.4.2

**Closed** 2020-06-28 16:16 UTC
